const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const cities_of_dolnoslaskie_province = [
  "Aleksandrowice",
  "Antoniów",
  "Babin",
  "Bagieniec",
  "Bagno",
  "Baldwinowice",
  "Baranowice",
  "Baranowice",
  "Barcinek",
  "Bardo",
  "Barkowo",
  "Bartków",
  "Bartków",
  "Bartnica",
  "Bartoszowa",
  "Bartoszów",
  "Bartoszówek",
  "Barycz",
  "Baszyn",
  "Bądzów",
  "Bąków",
  "Bąków",
  "Bełcz Górny",
  "Bełcz Mały",
  "Będkowice",
  "Będzin",
  "Biadaszka",
  "Biała",
  "Białawy",
  "Białawy Małe",
  "Białe Błoto",
  "Białków",
  "Białków",
  "Białobrzezie",
  "Białogórze",
  "Białołęka",
  "Białopole",
  "Biegoszów",
  "Bielany",
  "Bielany Wrocławskie",
  "Bielawa",
  "Bierkowice",
  "Bierutów",
  "Bierzyce",
  "Biestrzyków",
  "Biskupice",
  "Bogatynia",
  "Bogdanów",
  "Bogusławice",
  "Boguszów-Gorce",
  "Boguszyce",
  "Bolesławiec",
  "Boleścin",
  "Bolków",
  "Borowice",
  "Borów",
  "Borzynowo",
  "Bożków",
  "Brochocin",
  "Brukalice",
  "Brunów",
  "Brzeg Dolny",
  "Brzezia Łąka",
  "Brzezie",
  "Brzezina Sułowska-Osada",
  "Brzeźno",
  "Budziwojów",
  "Budzów",
  "Bukowice",
  "Burkatów",
  "Bychowo",
  "Bystrzyca",
  "Bystrzyca Kłodzka",
  "Chełmsko Śląskie",
  "Chobienia",
  "Chocianów",
  "Chocieszów",
  "Chojnów",
  "Chrośnica",
  "Ciechanowice",
  "Ciechów",
  "Ciepłowody",
  "Cieszków",
  "Czarny Bór",
  "Czerna",
  "Czernica",
  "Czerwona Woda",
  "Długołęka",
  "Dobroszyce",
  "Domaszków",
  "Duszniki-Zdrój",
  "Dziadowa Kłoda",
  "Dziećmorowice",
  "Dzierżoniów",
  "Dziwiszów",
  "Gaworzyce",
  "Gierałtów",
  "Głogów",
  "Głuszyca",
  "Głuszyca Górna",
  "Gniechowice",
  "Goczałków",
  "Goszcz",
  "Gościszów",
  "Góra",
  "Grabowno Wielkie",
  "Grębocice",
  "Gromadka",
  "Gryfów Śląski",
  "Henryków",
  "Iwiny",
  "Jaczów",
  "Janowice Wielkie",
  "Jaroszów",
  "Jaszkowa Dolna",
  "Jawor",
  "Jaworzyna Śląska",
  "Jedlina-Zdrój",
  "Jelcz-Laskowice",
  "Jelenia Góra",
  "Jerzmanowa",
  "Jeżów Sudecki",
  "Jordanów Śląski",
  "Jugów",
  "Kamieniec Wrocławski",
  "Kamieniec Ząbkowicki",
  "Kamienna Góra",
  "Karpacz",
  "Kąty Wrocławskie",
  "Kiełczów",
  "Kłodzko",
  "Kobierzyce",
  "Kotla",
  "Kowary",
  "Krosnowice",
  "Krośnice",
  "Kruszyn",
  "Krzeszów",
  "Kudowa-Zdrój",
  "Kunice",
  "Lądek-Zdrój",
  "Legnica",
  "Legnickie Pole",
  "Leśna",
  "Lubań",
  "Lubawka",
  "Lubiąż",
  "Lubin",
  "Lubomierz",
  "Ludwikowice Kłodzkie",
  "Lutomia Górna",
  "Lutynia",
  "Lwówek Śląski",
  "Łagiewniki",
  "Łagów",
  "Łomnica",
  "Malczyce",
  "Marcinkowice",
  "Marciszów",
  "Mieroszów",
  "Międzybórz",
  "Międzylesie",
  "Miękinia",
  "Milicz",
  "Milików",
  "Miłkowice",
  "Miłków",
  "Miłoszyce",
  "Mirków",
  "Mirsk",
  "Mojęcice",
  "Mokrzeszów",
  "Mościsko",
  "Mysłakowice",
  "Niemcza",
  "Nowa Ruda",
  "Nowogrodziec",
  "Nowy Kościół",
  "Obora",
  "Oborniki Śląskie",
  "Oleśnica",
  "Olszyna",
  "Oława",
  "Ołdrzychowice Kłodzkie",
  "Opolno Zdrój",
  "Osiecznica",
  "Osiek",
  "Ostroszowice",
  "Pastuchów",
  "Paszowice",
  "Pęgów",
  "Piechowice",
  "Pieńsk",
  "Pieszyce",
  "Piława Dolna",
  "Piława Górna",
  "Piotrowice",
  "Pisarzowice",
  "Pobiedna",
  "Podgórzyn",
  "Polanica-Zdrój",
  "Polkowice",
  "Porajów",
  "Proboszczów",
  "Prochowice",
  "Prusice",
  "Przemków",
  "Przeworno",
  "Psary",
  "Pszenno",
  "Raciborowice Górne",
  "Radków",
  "Radwanice",
  "Radwanice",
  "Roztoka",
  "Rudna",
  "Ruszowice",
  "Ruszów",
  "Serby",
  "Siechnice",
  "Siedlęcin",
  "Siekierczyn",
  "Skokowa",
  "Smolec",
  "Snowidza",
  "Sobótka",
  "Sosnówka",
  "Srebrna Góra",
  "Stanowice",
  "Stara Kamienica",
  "Stare Bogaczowice",
  "Stary Węgliniec",
  "Stolec",
  "Stradomia Wierzchnia",
  "Stronie Śląskie",
  "Strzegom",
  "Strzelin",
  "Strzeszów",
  "Sulików",
  "Sułów",
  "Syców",
  "Szczawno-Zdrój",
  "Szczepanów",
  "Szczodre",
  "Szczytna",
  "Szklarska Poręba",
  "Ściegny",
  "Ścinawa",
  "Ścinawka Dolna",
  "Ścinawka Średnia",
  "Środa Śląska",
  "Świdnica",
  "Świebodzice",
  "Świeradów-Zdrój",
  "Świerzawa",
  "Święta Katarzyna",
  "Świętoszów",
  "Tomaszów Bolesławiecki",
  "Trzebień",
  "Trzebieszowice",
  "Trzebnica",
  "Twardogóra",
  "Tyniec Mały",
  "Ubocze",
  "Uciechów",
  "Walim",
  "Wałbrzych",
  "Wąsosz",
  "Węgliniec",
  "Wiązów",
  "Wierzbno",
  "Wilczyce",
  "Wilkanów",
  "Wilków-Osiedle",
  "Wińsko",
  "Witków",
  "Witoszów Dolny",
  "Wleń",
  "Wojbórz",
  "Wojcieszów",
  "Wojcieszyce",
  "Wolibórz",
  "Wołów",
  "Wrocław",
  "Wykroty",
  "Wysoka",
  "Zagrodno",
  "Zaręba",
  "Zawidów",
  "Zawonia",
  "Ząbkowice Śląskie",
  "Zebrzydowa",
  "Zgorzelec",
  "Ziębice",
  "Złotoryja",
  "Złoty Stok",
  "Żarów",
  "Żerniki Wrocławskie",
  "Żmigród",
  "Żórawina",
];

const cities_of_kujawsko_pomorskie_province = [
  "Adaminowo",
  "Adamki",
  "Adamkowo",
  "Adamowo",
  "Adamowo",
  "Adamowo",
  "Agnieszkowo",
  "Aleksandrowiec",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrów Kujawski",
  "Altana",
  "Ameryczka",
  "Anielewo",
  "Anielin",
  "Anieliny",
  "Annowo",
  "Annowo",
  "Annowo",
  "Annowo",
  "Antoniewo",
  "Antoniewo",
  "Antoniewo",
  "Anusin",
  "Arciszewo",
  "Ariany",
  "Arturowo",
  "Augustowo",
  "Augustowo",
  "Augustynowo",
  "Baba",
  "Baba",
  "Babie Ławy",
  "Bachorce",
  "Bachorza",
  "Bachorzewo",
  "Bachotek",
  "Bagienica",
  "Bagniewko",
  "Bagniewo",
  "Bagno",
  "Bajerze",
  "Balczewo",
  "Balice",
  "Balin",
  "Bałdowo",
  "Baranowo",
  "Barany",
  "Barcikowo",
  "Barcin",
  "Barcin Wieś",
  "Barłogi",
  "Bartlewo",
  "Bartłomiejowice",
  "Bartniczka",
  "Bartniki",
  "Bartoszewice",
  "Baruchowo",
  "Batkowo",
  "Bąbolin",
  "Bąbowo",
  "Bągart",
  "Bąkowo",
  "Bąkowo",
  "Bąkowski Młyn",
  "Bełszewo",
  "Bełszewo Kolonia",
  "Bernardowo",
  "Bertowo",
  "Beszyn",
  "Będzeń",
  "Będzitowo",
  "Będzitówek",
  "Bętlewo",
  "Białe Błota",
  "Białe Błota",
  "Białe Błota",
  "Białe Błota-Dębówiec",
  "Białowieża",
  "Białożewin",
  "Biały Bór",
  "Bielczyny",
  "Bielica",
  "Bielska Struga",
  "Bileńska Kolonia",
  "Bilno",
  "Blizawy",
  "Bławaty",
  "Bobrowniki",
  "Bocień",
  "Bodzanówek",
  "Bodzia",
  "Boniewo",
  "Borki",
  "Borowo",
  "Brodnica",
  "Bronisław",
  "Bród Kamienny",
  "Bródzki",
  "Brześć Kujawski",
  "Brzoza",
  "Brzoza",
  "Brzozie",
  "Brzozówka",
  "Buczek",
  "Buczkowo",
  "Buk Góralski",
  "Bukowiec",
  "Bydgoszcz",
  "Byłyczek",
  "Bysław",
  "Cekcyn",
  "Cepno",
  "Chalno",
  "Charszewo",
  "Chełmica Duża",
  "Chełmiczki",
  "Chełmno",
  "Chełmża",
  "Choceń",
  "Chodecz",
  "Chraplewo",
  "Ciechocinek",
  "Ciele",
  "Cielęta",
  "Cierpice",
  "Cierplewo",
  "Czajno",
  "Czapelki",
  "Czarne",
  "Czarny Las",
  "Czarże",
  "Czeczewo",
  "Czerniewice",
  "Czernikowo",
  "Czerskie Rumunki",
  "Czewujewo",
  "Dąb Wielki",
  "Dąbek",
  "Dąbrowa",
  "Dąbrowa Chełmińska",
  "Dąbrówka",
  "Dębianki",
  "Dębniaki",
  "Dębołęka",
  "Dębowo",
  "Dobrcz",
  "Dobre",
  "Dobre-Kolonia",
  "Dobrzejewice",
  "Dobrzyń nad Wisłą",
  "Dolna Grupa",
  "Dolne Morgi",
  "Drążno",
  "Drzycim",
  "Dulsk",
  "Dulsk",
  "Dylewo",
  "Działyń",
  "Dziechowo",
  "Dziekcz",
  "Dziemionna",
  "Falk",
  "Fojutowo",
  "Gaj",
  "Gąsawa",
  "Gąski",
  "Giżynek",
  "Głęboczek",
  "Głogowo",
  "Głuszyn",
  "Gniewkowo",
  "Gniewkówiec",
  "Godziszka",
  "Gogolinek",
  "Golska Huta",
  "Golub-Dobrzyń",
  "Gołębiewo",
  "Gołoty",
  "Gołuchowo",
  "Goryń",
  "Gorzeszyn",
  "Gostycyn",
  "Góra",
  "Górsk",
  "Górzno",
  "Grębocin",
  "Gródek",
  "Gruczno",
  "Grudziądz",
  "Grupa",
  "Gruta",
  "Grzywna",
  "Inowrocław",
  "Izbica Kujawska",
  "Jabłonowo Pomorskie",
  "Jaksice",
  "Janikowo",
  "Janowiec Wielkopolski",
  "Jeżewo",
  "Kamień Krajeński",
  "Karbowo",
  "Kcynia",
  "Kikół",
  "Kołaczkowo",
  "Koronowo",
  "Kotomierz",
  "Kowal",
  "Kowalewo Pomorskie",
  "Krobia",
  "Kruszwica",
  "Książki",
  "Laskowice",
  "Lipno",
  "Lisewo",
  "Lniano",
  "Lubicz Dolny",
  "Lubicz Górny",
  "Lubień Kujawski",
  "Lubiewo",
  "Lubraniec",
  "Łabiszyn",
  "Łasin",
  "Łochowo",
  "Łubianka",
  "Łysomice",
  "Maksymilianowo",
  "Mała Nieszawka",
  "Mąkowarsko",
  "Mogilno",
  "Mrocza",
  "Nakło nad Notecią",
  "Nasiegniewo",
  "Niemcz",
  "Nieszawa",
  "Nowa Wieś",
  "Nowa Wieś Wielka",
  "Nowe",
  "Obrowo",
  "Osie",
  "Osiek",
  "Osiek Nad Wisłą",
  "Osielsko",
  "Osięciny",
  "Osówiec",
  "Ostrowite",
  "Pakość",
  "Papowo Toruńskie",
  "Paterek",
  "Piechcin",
  "Pigża",
  "Piotrków Kujawski",
  "Potulice",
  "Pruszcz",
  "Raciążek",
  "Radomin",
  "Radziejów",
  "Radzyń Chełmiński",
  "Rogowo",
  "Rozgarty",
  "Rynarzewo",
  "Rypin",
  "Sadki",
  "Serock",
  "Sępólno Krajeńskie",
  "Skępe",
  "Skrwilno",
  "Służewo",
  "Solec Kujawski",
  "Strzelno",
  "Sypniewo",
  "Szpetal Górny",
  "Szubin",
  "Ślesin",
  "Śliwice",
  "Świecie",
  "Świedziebnia",
  "Świekatowo",
  "Tłuchowo",
  "Toruń",
  "Tuchola",
  "Tuczno",
  "Turzno",
  "Unisław",
  "Wałycz",
  "Warlubie",
  "Wąbrzeźno",
  "Wielgie",
  "Wieniec",
  "Wierzchosławice",
  "Więcbork",
  "Włocławek",
  "Występ",
  "Zamość",
  "Zławieś Mała",
  "Złotniki Kujawskie",
  "Złotoria",
  "Żnin",
  "Żołędowo",
];

const cities_of_lubelskie_province = [
  "Abramowice Kościelne",
  "Abramowice Prywatne",
  "Abramów",
  "Abramów",
  "Adamki",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamówka",
  "Adampol",
  "Adelina",
  "Adelina",
  "Adolfin",
  "Agatówka",
  "Albertów",
  "Albinów Duży",
  "Albinów Mały",
  "Aleksandria Krzywowolska",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów Czwarty",
  "Aleksandrów Drugi",
  "Aleksandrów Pierwszy",
  "Aleksandrów Trzeci",
  "Aleksandrówka",
  "Aleksandrówka",
  "Aleksandrówka",
  "Aleksandrówka",
  "Aleksandrówka",
  "Alojzów",
  "Alojzów",
  "Amelin",
  "Amelin",
  "Ameryka",
  "Andrzejów",
  "Andrzejów",
  "Andrzejów",
  "Andrzejów Osada",
  "Andrzejów PGR",
  "Andrzejówka",
  "Andrzejówka",
  "Anielin",
  "Anielin",
  "Anielówka",
  "Anielpol",
  "Annobór",
  "Annobór-Kolonia",
  "Annopol",
  "Annopol",
  "Annopol",
  "Annopol",
  "Annów",
  "Annówka",
  "Anonin",
  "Antolin",
  "Antonin",
  "Antoniów-Kolonia",
  "Antoniówka",
  "Antoniówka",
  "Antoniówka",
  "Antoniówka",
  "Antonówka",
  "Antopol",
  "Anusin",
  "Augustówka",
  "Aurelin",
  "Babczyzna",
  "Babianka",
  "Babice",
  "Babin",
  "Babsk",
  "Baczków",
  "Bagno",
  "Bakus-Wanda",
  "Bałtów",
  "Bańkowszczyzna",
  "Barak",
  "Baraki",
  "Baraki",
  "Baraki",
  "Baran",
  "Baranica",
  "Baranów",
  "Baranówka",
  "Barbarówka",
  "Barchaczów",
  "Barki",
  "Barłogi",
  "Bartłomiejowice",
  "Baszki",
  "Batorz Drugi",
  "Batorz Pierwszy",
  "Batorz-Kolonia",
  "Bazar",
  "Bedlno",
  "Bełżec",
  "Bełżyce",
  "Berejów",
  "Bereść",
  "Bereza",
  "Berezówka",
  "Bereżnica",
  "Bezek",
  "Bezwola",
  "Bezwola Górne",
  "Bezwola Iski",
  "Biadaczka",
  "Biała",
  "Biała Druga",
  "Biała Pierwsza",
  "Biała Podlaska",
  "Białka",
  "Białka",
  "Białka-Kolonia",
  "Białki Górne",
  "Białoskóry",
  "Białowoda",
  "Białystok",
  "Biesiadki",
  "Biłgoraj",
  "Biszcza",
  "Blizocin",
  "Bobowiska",
  "Boby-Księże",
  "Bochotnica",
  "Bodaczów",
  "Bogucin",
  "Bogusław",
  "Bordziłówka",
  "Borków",
  "Borowina",
  "Borowina Sitaniecka",
  "Borownica",
  "Borucicha",
  "Boruń",
  "Boża Wola",
  "Brzozowica Duża",
  "Bukowina",
  "Bychawa",
  "Chełm",
  "Chmielek",
  "Chodel",
  "Ciecierzyn",
  "Cyców",
  "Czemierniki",
  "Dąbrowica",
  "Dęblin",
  "Dołhobyczów",
  "Dubeczno",
  "Dys",
  "Fajsławice",
  "Firlej",
  "Frampol",
  "Franciszków",
  "Garbów I",
  "Garbów II",
  "Godziszów Pierwszy",
  "Gołąb",
  "Góra Puławska",
  "Hańsk Pierwszy",
  "Horodło",
  "Hrubieszów",
  "Huta Dąbrowa",
  "Izbica",
  "Jabłoń",
  "Jakubowice Konińskie",
  "Janowiec",
  "Janów Lubelski",
  "Janów Podlaski",
  "Jarosławiec",
  "Jawidz",
  "Józefów",
  "Kalinowice",
  "Kamionka",
  "Karczmiska Pierwsze",
  "Kazimierz Dolny",
  "Klementowice",
  "Kłoczew",
  "Kock",
  "Kodeń II",
  "Komarówka Podlaska",
  "Konopnica",
  "Konstantynów",
  "Końskowola",
  "Krasnobród",
  "Krasnystaw",
  "Kraśnik",
  "Krępiec",
  "Krężnica Jara",
  "Krynka",
  "Krzywda",
  "Księżpol",
  "Kurów",
  "Lubartów",
  "Lublin",
  "Lubycza Królewska",
  "Łabunie",
  "Łabuńki Pierwsze",
  "Łaszczów",
  "Łaszczówka",
  "Łazy",
  "Łęczna",
  "Łomazy",
  "Łukowa",
  "Łuków",
  "Majdan Górny",
  "Małaszewicze",
  "Markuszów",
  "Mełgiew",
  "Mętów",
  "Michów",
  "Międzyrzec Podlaski",
  "Milanów",
  "Milejów-Osada",
  "Mircze",
  "Modliborzyce",
  "Mokre",
  "Motycz",
  "Nałęczów",
  "Nasutów",
  "Niedrzwica Duża",
  "Niedrzwica Kościelna",
  "Nieledew",
  "Niemce",
  "Okrzeja",
  "Oleśniki",
  "Opole Lubelskie",
  "Orchówek",
  "Osiny",
  "Ostrów Lubelski",
  "Panieńszczyzna",
  "Parczew",
  "Piaski",
  "Piotrowice",
  "Piszczac",
  "Płoskie",
  "Pokrówka",
  "Poniatowa",
  "Potok Górny",
  "Puławy",
  "Radawiec Duży",
  "Radzyń Podlaski",
  "Rakowiska",
  "Rejowiec",
  "Rejowiec Fabryczny",
  "Rogóźno",
  "Rossosz",
  "Rozkopaczew",
  "Ruda-Huta",
  "Rudka Kozłowiecka",
  "Ryki",
  "Sawin",
  "Serokomla",
  "Siennica Nadolna",
  "Sitaniec",
  "Skierbieszów",
  "Sławacinek Stary",
  "Sławatycze",
  "Sól",
  "Stężyca",
  "Stoczek Łukowski",
  "Stróża-Kolonia",
  "Strzyżów",
  "Suchowola",
  "Susiec",
  "Suszno",
  "Szczebrzeszyn",
  "Świdnik",
  "Tarnogród",
  "Terespol",
  "Tereszpol-Zaorenda",
  "Tomaszów Lubelski",
  "Trawniki",
  "Tuczna",
  "Turka",
  "Turobin",
  "Turów",
  "Tyszowce",
  "Ulhówek",
  "Urzędów",
  "Wąwolnica",
  "Werbkowice",
  "Wierzbica-Osiedle",
  "Wisznice",
  "Włodawa",
  "Wohyń",
  "Wojcieszków",
  "Wojsławice",
  "Wola Niemiecka",
  "Wola Przybysławska",
  "Wola Uhruska",
  "Zakrzówek",
  "Zamch",
  "Zamość",
  "Zawada",
  "Zwierzyniec",
  "Żyrzyn",
];

const cities_of_lubuskie_province = [
  "Babimost",
  "Baczyna",
  "Bagniewo",
  "Bagno",
  "Baranowice",
  "Barcikowice",
  "Bargów",
  "Będów",
  "Białcz",
  "Białczyk",
  "Biecz",
  "Biedrzychowice",
  "Bieganów",
  "Bledzew",
  "Błotnica",
  "Bobowicko",
  "Bobrowice",
  "Boczów",
  "Bogaczów",
  "Bogdaniec",
  "Bojadła",
  "Boryszyn",
  "Bożnów",
  "Bracikowo",
  "Bronowice",
  "Brożek",
  "Brójce",
  "Brzeźnica",
  "Brzeźnica",
  "Brzeźno",
  "Brzeźno",
  "Brzozowa",
  "Buchałów",
  "Buczek",
  "Budachów",
  "Budachów-Kolonia",
  "Budoradz",
  "Budziechów",
  "Bukowica",
  "Bukowina",
  "Bukowina Bobrzańska",
  "Bytnica",
  "Bytom Odrzański",
  "Chełmsko",
  "Chlebów",
  "Chłopiny",
  "Chociejów",
  "Chotków",
  "Chrapów",
  "Chromów",
  "Chudzowice",
  "Chwalęcice",
  "Chwalim",
  "Chwaliszowice",
  "Ciecierzyn",
  "Ciemnice",
  "Cybinka",
  "Czarnowice",
  "Czarnowo",
  "Czarnów",
  "Czciradz",
  "Czerwieńsk",
  "Czyżewo",
  "Dąbroszyn",
  "Dąbrowno",
  "Dąbrówka Wielkopolska",
  "Deszczno",
  "Dębogóra",
  "Dębowiec",
  "Dobiegniew",
  "Dobre",
  "Dobrochów",
  "Drezdenko",
  "Drogomin",
  "Droniki",
  "Drzonków",
  "Duraczewo",
  "Gębice",
  "Gorzów Wielkopolski",
  "Goszczanowiec",
  "Goszczanówko",
  "Gościnowo",
  "Gozdnica",
  "Górka",
  "Górzyca",
  "Grąsy",
  "Grodziszcze",
  "Grzmikoło",
  "Gubin",
  "Gubinek",
  "Guzów",
  "Iłowa",
  "Jagłowice",
  "Janczewo",
  "Jasień",
  "Jeleniów",
  "Jenin",
  "Jesionka",
  "Jeziorki",
  "Jędrzychowice",
  "Kalinowo",
  "Kaliszkowice",
  "Kamienna",
  "Kamień",
  "Kamionka",
  "Kaniów",
  "Kargowa",
  "Kępa Zagajna",
  "Kępiny",
  "Kępsko",
  "Klenica",
  "Kleszczewo",
  "Kłodawa",
  "Kłopotowo",
  "Kochań",
  "Kocin",
  "Kolonia Glisno",
  "Konin Żagański",
  "Konotop",
  "Kosieczyn",
  "Kostrzyn nad Odrą",
  "Koźminek",
  "Kożuchów",
  "Krasowiec",
  "Krępa",
  "Krosno Odrzańskie",
  "Krzepielów",
  "Krzeszyce",
  "Krześniczka",
  "Krzyszczyna",
  "Kukadło",
  "Kuligowo",
  "Kunice",
  "Kupienino",
  "Lasek",
  "Laski Dolne",
  "Lasocin",
  "Lemierzyce",
  "Leszno Górne",
  "Lgiń",
  "Lipie Góry",
  "Lipinki Łużyckie",
  "Lipki Małe",
  "Lipki Wielkie",
  "Lubiatów",
  "Lubinicko",
  "Lubniewice",
  "Lubogoszcz",
  "Lubsko",
  "Lutol Suchy",
  "Łagów",
  "Łąkomin",
  "Łęknica",
  "Łężyca",
  "Łochowice",
  "Ługi",
  "Małe Osiedle",
  "Małomice",
  "Marcinów",
  "Marianki",
  "Maszków",
  "Międzylesie",
  "Międzyrzecz",
  "Miłaków",
  "Miłów",
  "Mirostowice Dolne",
  "Modrzyca",
  "Mosina",
  "Murzynowo",
  "Myszęcin",
  "Niedoradz",
  "Nietków",
  "Nowa Jabłona",
  "Nowa Kopernia",
  "Nowa Sól",
  "Nowe Czaple",
  "Nowe Kramsko",
  "Nowe Miasteczko",
  "Nowe Strącze",
  "Nowiny Wielkie",
  "Nowogród Bobrzański",
  "Nowy Kisielin",
  "Obłotne",
  "Ochla",
  "Oksza",
  "Orzelec",
  "Osiedle Poznańskie",
  "Osowa Sień",
  "Ostrów",
  "Ośno Lubuskie",
  "Otyń",
  "Pamięcin",
  "Piaski",
  "Pietrzyków",
  "Płoty",
  "Podmokle Małe",
  "Połęcko",
  "Połupin",
  "Prądocinek",
  "Przyborów",
  "Przybymierz",
  "Przylaski",
  "Przylep",
  "Przytoczna",
  "Pszczew",
  "Pyrnik",
  "Racula",
  "Radęcin",
  "Radocin",
  "Radowice",
  "Raków",
  "Rańsko",
  "Romanówek",
  "Różanki",
  "Rudawica",
  "Rybaki",
  "Rybocice",
  "Rychlik",
  "Rzepin",
  "Samsonki",
  "Sarbia",
  "Sarbinowo",
  "Sidłów",
  "Sieciejów",
  "Siedlisko",
  "Sieniawa",
  "Sieniawa Żarska",
  "Sienno",
  "Skwierzyna",
  "Sława",
  "Słocina",
  "Słońsk",
  "Słowin",
  "Słubice",
  "Smardzewo",
  "Spokojna",
  "Stare Czaple",
  "Stare Kurowo",
  "Stare Osieczno",
  "Stare Strącze",
  "Stargard Gubiński",
  "Stary Kisielin",
  "Stary Raduszec",
  "Struga",
  "Strychy",
  "Strzelce Krajeńskie",
  "Stypułów",
  "Suchleb",
  "Suchodół",
  "Sudoł",
  "Sulechów",
  "Sulęcin",
  "Szczaniec",
  "Szlichtyngowa",
  "Szprotawa",
  "Szprotawka",
  "Szyba",
  "Świdnica",
  "Świebodzin",
  "Świecko",
  "Tarnów Jezierny",
  "Tawęcin",
  "Templewo PGR",
  "Tomaszowo",
  "Torzym",
  "Trzciel",
  "Trzebiechów-Leśniczówka",
  "Trzebiel",
  "Trzebule",
  "Trzemeszno",
  "Tuchola Żarska",
  "Tuplice",
  "Turów",
  "Urzuty",
  "Wałowice",
  "Wawrów",
  "Wędrzyn",
  "Wiechlice",
  "Wilkanowo",
  "Witnica",
  "Witosław",
  "Wołogoszcz",
  "Wróblów",
  "Wrzesiny",
  "Wschowa",
  "Wygnańczyce",
  "Wymiarki",
  "Wysokie",
  "Wystok",
  "Zarzyń",
  "Zawada",
  "Zbąszynek",
  "Zielomyśl",
  "Zielona Góra",
  "Zwierzyn",
  "Zwierzyniec",
  "Żabczyn",
  "Żagań",
  "Żary",
  "Żydowo",
];

const cities_of_lodzkie_province = [
  "Adamka",
  "Adamki",
  "Adamowice",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adelinów",
  "Adolfinów",
  "Adolfów",
  "Afryka",
  "Agnopol",
  "Albertów",
  "Albertów",
  "Albertów",
  "Albinów",
  "Aleksandria",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów Łódzki",
  "Aleksandrówek",
  "Aleksandrówek",
  "Aleksandrówek",
  "Aleksandrówka",
  "Aleksandrówka",
  "Alfonsów",
  "Alfonsów",
  "Alfonsów",
  "Ambrożew",
  "Amelin",
  "Anastazew",
  "Anastazów",
  "Andrespol",
  "Andrzejów",
  "Andrzejów",
  "Andrzejów",
  "Anielin",
  "Anielin",
  "Anielin",
  "Anielin",
  "Anielin",
  "Anielin",
  "Anielin Swędowski",
  "Anielów",
  "Anin",
  "Annetów",
  "Annolesie",
  "Annopol Duży",
  "Annopol Mały",
  "Annopole Nowe",
  "Annopole Stare",
  "Annosław",
  "Annów",
  "Annów",
  "Antolin",
  "Antoniew",
  "Antoniew",
  "Antoniew",
  "Antoniew",
  "Antonin",
  "Antonina",
  "Antoninów",
  "Antoninów",
  "Antoniów",
  "Antoniów",
  "Antoniów",
  "Antoniówka",
  "Antoniówka",
  "Antopol",
  "Anusin",
  "Anusin",
  "Apolinów",
  "Apolonia",
  "Apolonka",
  "Arkadia",
  "Astachowice",
  "Augustopol",
  "Augustów",
  "Augustów",
  "Augustynów",
  "Augustynów",
  "Augustynów",
  "Babczów",
  "Babice",
  "Babichy",
  "Babiniec",
  "Babiniec",
  "Babsk",
  "Baby",
  "Bagatelka",
  "Balcerów",
  "Balików",
  "Balin",
  "Balków",
  "Bałdrzychów",
  "Bałucz",
  "Barany",
  "Barczew",
  "Barczkowice",
  "Bardzinek",
  "Bardzynin",
  "Barkowice",
  "Barkowice Mokre",
  "Bartochów",
  "Bartochów Brzezinka",
  "Bartochów Kolonia",
  "Bartolin",
  "Bartoszówka",
  "Barycz",
  "Baszków",
  "Bądków",
  "Bądzyń",
  "Bąki",
  "Bąkowa Góra",
  "Bąkowiec",
  "Bąków Górny",
  "Bechcice-Kolonia",
  "Bechcice-Parcela",
  "Bechcice-Wieś",
  "Bedlno",
  "Bedlno Kamieniec",
  "Bedlno Wieś",
  "Bednary",
  "Bednary-Kolonia",
  "Bednarze",
  "Bedoń Przykościelny",
  "Bedoń Wieś",
  "Beleń",
  "Bełchatów",
  "Bełchów",
  "Bełdów Krzywa Wieś",
  "Beresie Małe",
  "Bery",
  "Besiekierz Nawojowy",
  "Besiekierz Rudny",
  "Bęczkowice Wydryniwa",
  "Będków",
  "Będków",
  "Będków",
  "Będzelin",
  "Będzyn",
  "Biadaszki",
  "Biała",
  "Biała",
  "Biała",
  "Biała Druga",
  "Biała Góra",
  "Biała Góra",
  "Biała Pierwsza",
  "Biała Rawska",
  "Biała Róża",
  "Biała-Parcela",
  "Białaczów",
  "Białkowice",
  "Białocin",
  "Biały Ług",
  "Białynin-Latków",
  "Białynin-Podbór",
  "Białynin-Południe",
  "Bibianów",
  "Bielawki",
  "Bielawy",
  "Blizin",
  "Blok Dobryszyce",
  "Błaszki",
  "Błonie",
  "Błonie",
  "Bobiecko",
  "Bobrowniki",
  "Boginia",
  "Bogoria Pofolwarczna",
  "Bogumiłowice",
  "Bogusławki Małe",
  "Bolesławów",
  "Bratoszewice",
  "Brzeziny",
  "Buczek",
  "Bukowiec",
  "Burzenin",
  "Czarnocin",
  "Czarnożyły",
  "Czechy",
  "Dąbrowa",
  "Dłutów",
  "Dobroń",
  "Domaniewice",
  "Drzewica",
  "Działoszyn",
  "Dzietrzkowice",
  "Dzietrzniki",
  "Galewice",
  "Gałków Mały",
  "Gidle",
  "Głowno",
  "Głuchów",
  "Gomunice",
  "Gorzkowice",
  "Grabów",
  "Jeżów",
  "Justynów",
  "Kamieńsk",
  "Kleszczów",
  "Kolonia Wola Zaradzyńska",
  "Koluszki",
  "Konstantynów Łódzki",
  "Kraszkowice",
  "Krośniewice",
  "Ksawerów",
  "Kutno",
  "Lipce Reymontowskie",
  "Lutomiersk",
  "Lututów",
  "Łask",
  "Łęczyca",
  "Łowicz",
  "Łódź",
  "Łubnice",
  "Łyszkowice",
  "Maków",
  "Mierzyce",
  "Mokrsko",
  "Moszczenica",
  "Mysłaków",
  "Niechcice",
  "Nowy Glinnik",
  "Opoczno",
  "Osiedle Niewiadów",
  "Osjaków",
  "Ozorków",
  "Pabianice",
  "Pajęczno",
  "Pątnów",
  "Piątek",
  "Piotrków Trybunalski",
  "Pławno",
  "Poddębice",
  "Przedbórz",
  "Przygłów",
  "Radomsko",
  "Radoszewice",
  "Rawa Mazowiecka",
  "Rąbień",
  "Rogów",
  "Rokiciny-Kolonia",
  "Rozprza",
  "Ruda",
  "Rusiec",
  "Rzeczyca",
  "Rzgów",
  "Siemkowice",
  "Sieradz",
  "Skierniewice",
  "Skomlin",
  "Smardzewice",
  "Sokolniki",
  "Starowa Góra",
  "Stryków",
  "Strzałków",
  "Strzelce Wielkie",
  "Sulejów",
  "Sulmierzyce",
  "Szadek",
  "Szczerców",
  "Tomaszów Mazowiecki",
  "Trębaczew",
  "Tuszyn",
  "Ujazd",
  "Uniejów",
  "Warta",
  "Widawa",
  "Wieluń",
  "Wieruszów",
  "Wierzchlas",
  "Wiśniowa Góra",
  "Witonia",
  "Włodzimierzów",
  "Wola Krzysztoporska",
  "Wola Moszczenicka",
  "Wolbórz",
  "Zduńska Wola",
  "Zelów",
  "Zgierz",
  "Złoczew",
  "Żarnów",
  "Żychlin",
];

const cities_of_malopolskie_province = [
  "Alwernia",
  "Andrychów",
  "Babice",
  "Babice",
  "Bachowice",
  "Balice",
  "Balin",
  "Bańska Niżna",
  "Bańska Wyżna",
  "Bartkowa-Posadowa",
  "Barwałd Górny",
  "Barwałd Średni",
  "Biała Niżna",
  "Białka Tatrzańska",
  "Biały Dunajec",
  "Bibice",
  "Bielany",
  "Bilsko",
  "Binarowa",
  "Biskupice Radłowskie",
  "Bochnia",
  "Bogumiłowice",
  "Bolechowice",
  "Bolęcin",
  "Borek",
  "Borek Szlachecki",
  "Borzęcin",
  "Borzęta",
  "Bruśnik",
  "Brzesko",
  "Brzeszcze",
  "Brzezie",
  "Brzezinka",
  "Brzezna",
  "Brzeźnica",
  "Brzozówka",
  "Bucze",
  "Bukowina Tatrzańska",
  "Bukowno",
  "Bulowice",
  "Burzyn",
  "Bysina",
  "Bystra",
  "Chabówka",
  "Chechło",
  "Chełmek",
  "Chełmiec",
  "Chochołów",
  "Chocznia",
  "Chojnik",
  "Chrzanów",
  "Cieniawa",
  "Czarny Dunajec",
  "Czchów",
  "Czermna",
  "Czerna",
  "Czernichów",
  "Czerwienne",
  "Czułów",
  "Dąbrowa Tarnowska",
  "Dębno",
  "Dobczyce",
  "Dobra",
  "Droginia",
  "Dulowa",
  "Dzianisz",
  "Dziewin",
  "Filipowice",
  "Florynka",
  "Frydman",
  "Frydrychowice",
  "Gierałtowice",
  "Głębowice",
  "Głogoczów",
  "Gorenice",
  "Gorlice",
  "Gronków",
  "Groń",
  "Gruszów Wielki",
  "Grybów",
  "Grywałd",
  "Harbutowice",
  "Ilkowice",
  "Inwałd",
  "Iwkowa",
  "Jabłonka",
  "Jadowniki",
  "Jaroszowice",
  "Jaroszowiec",
  "Jasienica",
  "Jasienna",
  "Jastrzębia",
  "Jaśkowice",
  "Jawiszowice",
  "Jerzmanowice",
  "Jodłownik",
  "Jordanów",
  "Juszczyn",
  "Kacwin",
  "Kalwaria Zebrzydowska",
  "Kamionka Wielka",
  "Kęty",
  "Klecza Dolna",
  "Klęczany",
  "Klikuszowa",
  "Kluszkowce",
  "Konary",
  "Koniuszowa",
  "Koszyce Wielkie",
  "Koźmice Wielkie",
  "Kraków",
  "Krempachy",
  "Krośnica",
  "Kryg",
  "Krynica-Zdrój",
  "Krzeczów",
  "Krzeszowice",
  "Krzywaczka",
  "Lachowice",
  "Lednica Górna",
  "Libiąż",
  "Lichwin",
  "Limanowa",
  "Lipinki",
  "Lipnica Wielka",
  "Lisia Góra",
  "Lubień",
  "Luszowice",
  "Łapsze Niżne",
  "Łącko",
  "Łąkta Dolna",
  "Łękawica",
  "Łętowe",
  "Łętowice",
  "Łętownia",
  "Łomnica Zdrój",
  "Łososina Dolna",
  "Łostówka",
  "Łuczyce",
  "Łukowica",
  "Maków Podhalański",
  "Marcinkowice",
  "Maszkienice",
  "Mędrzechów",
  "Mętków",
  "Miechów",
  "Miechów-Charsznica",
  "Miękinia",
  "Młoszowa",
  "Młynne",
  "Młyńczyska",
  "Modlniczka",
  "Mszalnica",
  "Mszana Dolna",
  "Mszana Górna",
  "Muchówka",
  "Muszyna",
  "Mystków",
  "Myślenice",
  "Naprawa",
  "Nawojowa",
  "Nawojowa Góra",
  "Nieczajna Górna",
  "Niedzica",
  "Niepołomice",
  "Nowa Biała",
  "Nowa Góra",
  "Nowe Bystre",
  "Nowy Sącz",
  "Nowy Targ",
  "Ochotnica Dolna",
  "Ochotnica Górna",
  "Olesno",
  "Olkusz",
  "Osiek",
  "Osiek",
  "Oświęcim",
  "Pcim",
  "Piekielnik",
  "Piotrowice",
  "Piwniczna-Zdrój",
  "Pleśna",
  "Podwilk",
  "Polanka Wielka",
  "Proszowice",
  "Proszówki",
  "Przeciszów",
  "Przeginia",
  "Przeginia Duchowna",
  "Przyborów",
  "Przydonica",
  "Przysietnica",
  "Przyszowa",
  "Ptaszkowa",
  "Raba Wyżna",
  "Rabka-Zdrój",
  "Racławice",
  "Radocza",
  "Radziszów",
  "Rączna",
  "Rdzawka",
  "Ropa",
  "Ropica Polska",
  "Rudawa",
  "Rupniów",
  "Rusocice",
  "Rybna",
  "Ryglice",
  "Rzepiennik Biskupi",
  "Rzozów",
  "Sąspów",
  "Sidzina",
  "Siedliska",
  "Siemiechów",
  "Siercza",
  "Siołkowa",
  "Skawa",
  "Skawica",
  "Skawina",
  "Skrzypne",
  "Słomniki",
  "Słopnice",
  "Słupiec",
  "Smęgorzów",
  "Sosnowice",
  "Spytkowice",
  "Sromowce Wyżne",
  "Staniątki",
  "Stanisław Górny",
  "Stare Bystre",
  "Stary Sącz",
  "Staszkówka",
  "Stronie",
  "Stróża",
  "Stróże",
  "Stryszawa",
  "Sucha Beskidzka",
  "Sułkowice",
  "Sułkowice",
  "Sułków",
  "Sułoszowa I",
  "Szarów",
  "Szczawa",
  "Szczawnica",
  "Szczucin",
  "Szymbark",
  "Szynwałd",
  "Świniarsko",
  "Tarnawa Dolna",
  "Tarnów",
  "Tenczyn",
  "Tenczynek",
  "Tęgoborze",
  "Tokarnia",
  "Toporzysko",
  "Trąbki",
  "Trzebinia",
  "Tuchów",
  "Turza",
  "Tworkowa",
  "Tylicz",
  "Tylmanowa",
  "Uście Gorlickie",
  "Wadowice",
  "Waksmund",
  "Węglówka",
  "Wieliczka",
  "Wielka Wieś",
  "Wielkie Drogi",
  "Wielmoża",
  "Wieprz",
  "Wierzchosławice",
  "Wilkowisko",
  "Wiśniowa",
  "Witów",
  "Włosań",
  "Wojakowa",
  "Wojnicz",
  "Wola Dębińska",
  "Wola Filipowska",
  "Wola Rzędzińska",
  "Wolbrom",
  "Woźniki",
  "Zabierzów",
  "Zabierzów Bocheński",
  "Zaborze",
  "Zaczarnie",
  "Zagórnik",
  "Zakliczyn",
  "Zakopane",
  "Zakrzów",
  "Zalesie",
  "Zaskale",
  "Zator",
  "Zawoja",
  "Zborowice",
  "Zembrzyce",
  "Zubrzyca Dolna",
  "Żarnówka",
  "Żurowa",
];

const cities_of_mazowieckie_province = [
  "Adamczycha",
  "Adamów Rososki",
  "Adamów-Wieś",
  "Adampol",
  "Adolfów",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrów",
  "Aleksandrów",
  "Aleksandrów Duży",
  "Aleksandrówka",
  "Aleksandrówka",
  "Alojzów",
  "Amelin",
  "Anastazew",
  "Anatolin",
  "Andrzejewo-Kolonie",
  "Andrzejewo-Zarzecze",
  "Andzin",
  "Antoniewo",
  "Antoniów",
  "Augustówek",
  "Baboszewo",
  "Baby",
  "Bachorza",
  "Baniocha",
  "Baranowo",
  "Białobrzegi",
  "Białobrzegi",
  "Bielawa",
  "Bielicha",
  "Bielsk",
  "Bieniewice",
  "Bieżuń",
  "Blizne Jasińskiego",
  "Błonie",
  "Bodzanów",
  "Borzęcin Duży",
  "Bramki",
  "Brańszczyk",
  "Brody-Parcele",
  "Brok",
  "Brudzeń Duży",
  "Brwinów",
  "Brzóza",
  "Cegłów",
  "Celestynów",
  "Chlewiska",
  "Chodów",
  "Chorzele",
  "Chotomów",
  "Chrzęsne",
  "Chylice-Kolonia",
  "Ciechanów",
  "Czerwińsk nad Wisłą",
  "Dąbrówka-Ług",
  "Dębe Wielkie",
  "Długosiodło",
  "Dobczyn",
  "Dobre",
  "Drobin",
  "Duczki",
  "Dylewo",
  "Dziekanów Leśny",
  "Garbatka-Letnisko",
  "Garwolin",
  "Gąbin",
  "Gąsocin",
  "Glina",
  "Glinojeck",
  "Głosków",
  "Gostynin",
  "Gozdowo",
  "Góra Kalwaria",
  "Gózd",
  "Granica",
  "Grodzisk Mazowiecki",
  "Groszowice",
  "Grójec",
  "Grudusk",
  "Halinów",
  "Hipolitów",
  "Hornówek",
  "Iłża",
  "Izabelin C",
  "Jabłonna",
  "Jadów",
  "Jasienica",
  "Jasieniec",
  "Jastrząb",
  "Jastrzębia",
  "Jedlińsk",
  "Jedlnia-Letnisko",
  "Jednorożec",
  "Józefosław",
  "Józefów",
  "Józefów",
  "Julianów",
  "Kadzidło",
  "Kałuszyn",
  "Kanie",
  "Karczew",
  "Karniewo",
  "Karolina",
  "Kiełpin",
  "Klaudyn",
  "Kobyłka",
  "Kołbiel",
  "Komorowo",
  "Komorów",
  "Konstancin-Jeziorna",
  "Kosów Lacki",
  "Kotuń",
  "Kozienice",
  "Kozłów Biskupi",
  "Krasnosielc",
  "Laski",
  "Laskowiec",
  "Latchorzew",
  "Legionowo",
  "Leszczydół-Nowiny",
  "Leszno",
  "Lipinki",
  "Lipniki",
  "Lipsko",
  "Lubowidz",
  "Łajski",
  "Łaskarzew",
  "Łazy",
  "Łąck",
  "Łęg Przedmiejski",
  "Łochów",
  "Łomianki",
  "Łosice",
  "Łyse",
  "Maciejowice",
  "Magdalenka",
  "Makowiec",
  "Maków",
  "Maków Mazowiecki",
  "Mała Wieś",
  "Małkinia Górna",
  "Marki",
  "Maszewo Duże",
  "Michałowice",
  "Michałów-Reginów",
  "Miedzna",
  "Międzyborów",
  "Miętne",
  "Milanówek",
  "Mińsk Mazowiecki",
  "Mława",
  "Młodzieszyn",
  "Mogielnica",
  "Mokobody",
  "Mordy",
  "Mrozy",
  "Mszczonów",
  "Mysiadło",
  "Myszyniec",
  "Nadarzyn",
  "Nadma",
  "Nasielsk",
  "Nieporęt",
  "Nowa Iwiczna",
  "Nowa Wieś",
  "Nowe Grocholice",
  "Nowe Iganie",
  "Nowe Lipiny",
  "Nowe Miasto",
  "Nowe Miasto nad Pilicą",
  "Nowe Pieścirogi",
  "Nowe Proboszczewice",
  "Nowy Duninów",
  "Nowy Dwór Mazowiecki",
  "Obryte",
  "Odrzywół",
  "Okuniew",
  "Olszewo-Borki",
  "Opacz Kolonia",
  "Orońsko",
  "Ostrołęka",
  "Ostrów Mazowiecka",
  "Ostrówek",
  "Ostrówek",
  "Otrębusy",
  "Otwock",
  "Owczarnia",
  "Ożarów Mazowiecki",
  "Paprotnia",
  "Parysów",
  "Piaseczno",
  "Piastów",
  "Pilawa",
  "Pionki",
  "Płochocin Osiedle",
  "Płock",
  "Płońsk",
  "Podebłocie",
  "Podkowa Leśna",
  "Policzna",
  "Pruszków",
  "Przasnysz",
  "Przysucha",
  "Przytyk",
  "Pułtusk",
  "Raciąż",
  "Radom",
  "Radzanowo",
  "Radzymin",
  "Raszyn",
  "Reguły",
  "Rębków",
  "Różan",
  "Ruchna",
  "Ruda Wielka",
  "Rybie",
  "Rząśnik",
  "Rzekuń",
  "Sade Budy",
  "Sadowne",
  "Sanniki",
  "Sarnaki",
  "Serock",
  "Siedlce",
  "Siennica",
  "Sierpc",
  "Skaryszew",
  "Skórzec",
  "Skrzyńsko",
  "Słubice",
  "Słupno",
  "Słupno",
  "Sobienie-Jeziory",
  "Sobolew",
  "Sochaczew",
  "Sochocin",
  "Sokołów Podlaski",
  "Stanisławice",
  "Stanisławów",
  "Stanisławów Pierwszy",
  "Stara Kornica",
  "Stara Niedziałka",
  "Stare Babice",
  "Staroźreby",
  "Stojadła",
  "Strzała",
  "Strzegowo",
  "Sucha",
  "Sulbiny",
  "Sulejówek",
  "Sułkowice",
  "Surowe",
  "Szreńsk",
  "Szydłowiec",
  "Świercze",
  "Świerże Górne",
  "Tarczyn",
  "Teresin",
  "Tłuszcz",
  "Trablice",
  "Trąbki",
  "Truskaw",
  "Trzcianka",
  "Ustanów",
  "Warka",
  "Warszawa",
  "Węgrów",
  "Wiązowna",
  "Wieliszew",
  "Wielogóra",
  "Wierzbica",
  "Wilga",
  "Wiskitki",
  "Wola Rasztowska",
  "Wola Rębkowska",
  "Wolkowe",
  "Wołomin",
  "Wólka Kozodawska",
  "Wsola",
  "Wyszków",
  "Wyszogród",
  "Zagościniec",
  "Zajezierze",
  "Zakroczym",
  "Zalesie Górne",
  "Ząbki",
  "Zbuczyn",
  "Zegrze",
  "Zielona",
  "Zielonka",
  "Złotokłos",
  "Zwoleń",
  "Żabieniec",
  "Żelechów",
  "Żelków-Kolonia",
  "Żółwin",
  "Żuromin",
  "Żyrardów",
];

const cities_of_opolskie_province = [
  "Aleksandrów",
  "Antoniów",
  "Babice",
  "Baborów",
  "Balcarzowice",
  "Baldwinowice",
  "Barut",
  "Barzyna",
  "Bażany",
  "Bąki",
  "Bąkowice",
  "Bąków",
  "Bąków-Brzezinka",
  "Bąków-Dobrzyny",
  "Bąków-Drogomin",
  "Bąków-Drzewiec",
  "Bernacice Górne",
  "Biadacz",
  "Biadacz-Brodnica",
  "Biała",
  "Białowieża-Suliszów",
  "Biechów",
  "Biechów-Radowice",
  "Biedrzychowice",
  "Bielice",
  "Bierawa",
  "Błażejowice Dolne",
  "Błotnica Strzelecka",
  "Boboluszki",
  "Bodzanowice",
  "Bodzanów",
  "Bodzanów Osiedle III",
  "Bogacica",
  "Bogacica-Krężel",
  "Borek",
  "Borek",
  "Borki",
  "Borki Małe",
  "Borkowice",
  "Branice",
  "Broniec",
  "Brynica",
  "Brynica-Markowe",
  "Brzeg",
  "Brzezina",
  "Brzezina",
  "Brzeziny Cieciułowskie",
  "Byczyna",
  "Bzionków",
  "Charbielin-Osiedle Pionierów",
  "Chmielowice",
  "Chocianowice",
  "Chorula",
  "Chróścice",
  "Chróścielów",
  "Chróścina",
  "Chróścina",
  "Chrząstowice",
  "Chudoba",
  "Cieciułów",
  "Cieszanowice",
  "Ciężkowice",
  "Cisek",
  "Czarnolas",
  "Czarnowąsy",
  "Czepielowice-Złotówka",
  "Ćwiercie",
  "Dalachów",
  "Daniec",
  "Dąbrowa",
  "Dąbrówka",
  "Dębie",
  "Dębowa",
  "Dębowiec",
  "Dębska Kuźnia",
  "Długomiłowice",
  "Dobiercice",
  "Dobieszowice",
  "Dobra-Nowy Bud",
  "Dobrodzień",
  "Dobrzeń Wielki",
  "Domaradz",
  "Domaszowice-Zalesie",
  "Domecko",
  "Drogoszów",
  "Dylaki",
  "Dytmarów",
  "Dziedzice",
  "Dziergowice",
  "Dziewkowice",
  "Folwark",
  "Giełczyce",
  "Gierałcice",
  "Gierałtowice",
  "Głogówek",
  "Głubczyce",
  "Głuchołazy",
  "Gogolin",
  "Golczowice",
  "Gorzów Śląski",
  "Gostomia",
  "Goszowice-Frączków",
  "Goświnowice",
  "Grabie",
  "Gracze",
  "Grądy",
  "Grodków",
  "Grodziec",
  "Grodziec",
  "Gryżów",
  "Gwoździce",
  "Hanuszów",
  "Iława",
  "Izbicko",
  "Jakubowice",
  "Jakubowice",
  "Januszkowice",
  "Jasiona",
  "Jaworzno",
  "Jelonki",
  "Jełowa",
  "Jemielnica",
  "Jeszkotle",
  "Jędrzychów",
  "Kadłub",
  "Kadłubiec",
  "Kamienica",
  "Kamień Śląski",
  "Karczów",
  "Karłowice",
  "Kędzierzyn-Koźle",
  "Kielcza",
  "Kietrz",
  "Kik",
  "Kluczbork",
  "Kolonowskie",
  "Komprachcice",
  "Kopalina",
  "Korfantów",
  "Kościerzyce",
  "Kowalowice-Nowy Dwór",
  "Kozłowice",
  "Krapkowice",
  "Krasiejów",
  "Krasna Góra",
  "Krotoszyn",
  "Krzyżowa Dolina",
  "Kubice",
  "Kuniów",
  "Kup",
  "Kurznie",
  "Kwiatków",
  "Leśnica",
  "Lewin Brzeski",
  "Lędziny",
  "Ligota Górna",
  "Ligota Tułowicka",
  "Lubnów",
  "Luboszyce",
  "Lubotyń",
  "Lubsza",
  "Ładza",
  "Łambinowice",
  "Łambinowice-Okopy",
  "Łany",
  "Łączany",
  "Łącznik",
  "Łąka Prudnicka",
  "Łosiów",
  "Łubniany",
  "Maciejowice-Grodziszcze",
  "Maciejów",
  "Makowice",
  "Mechnice",
  "Michałkowice",
  "Michałów",
  "Mikolin-Piaski",
  "Miłowice",
  "Miodary-Zielony Las",
  "Mokre-Kolonia",
  "Morów",
  "Moszczanka",
  "Murów",
  "Myszowice",
  "Myśliborzyce",
  "Myślina",
  "Nakło",
  "Namysłów",
  "Niekazanice",
  "Niemodlin",
  "Niezdrowice",
  "Niwki",
  "Niwki",
  "Nowa Wieś",
  "Nowa Wieś",
  "Nowa Wieś Głubczycka",
  "Nowaki",
  "Nowe Siołkowice",
  "Nowy Browiniec",
  "Nowy Las",
  "Nysa",
  "Ochodze",
  "Olesno",
  "Opole",
  "Osiek Grodkowski",
  "Osowiec",
  "Ostrożnica",
  "Otmice",
  "Otmuchów",
  "Ozimek",
  "Paczków",
  "Pakosławice",
  "Pawłowiczki",
  "Piotrowa",
  "Piotrowice Nyskie-Kraków",
  "Piotrówka",
  "Pludry",
  "Płużnica Wielka",
  "Pniewie",
  "Pogorzałka",
  "Pokój",
  "Polska Cerekiew",
  "Polska Nowa Wieś",
  "Popielów",
  "Praszka",
  "Prószków",
  "Prudnik",
  "Przełęk",
  "Przysiecz",
  "Przywory",
  "Psurów",
  "Racławice Śląskie",
  "Racławiczki",
  "Radziejów",
  "Raszowa",
  "Reńska Wieś",
  "Rozmierka",
  "Rozwadza",
  "Rożniątów",
  "Rożnów",
  "Rzędowice",
  "Rzędów",
  "Sidzina",
  "Siedlec",
  "Siedliska",
  "Sierosławice",
  "Skarbimierz Osiedle",
  "Skorogoszcz",
  "Skoroszyce",
  "Sławoszów",
  "Słupice-Spiny",
  "Sosnówka",
  "Staniszcze Małe",
  "Staniszcze Wielkie",
  "Stare Budkowice",
  "Stare Siołkowice",
  "Stary Ujazd",
  "Stary Ujazd-Kopanina",
  "Steblów",
  "Stobrawa",
  "Strojec",
  "Strzelce Opolskie",
  "Strzeleczki",
  "Strzelniki",
  "Szczedrzyk",
  "Szybowice",
  "Szymiszów",
  "Szymonków-Zielona Góra",
  "Śmicz",
  "Świerkle",
  "Tarnów Opolski",
  "Tokary",
  "Tułowice",
  "Tułowice Małe",
  "Ujazd",
  "Wachów",
  "Walce",
  "Wawelno",
  "Wichrów",
  "Wierzbica Górna",
  "Wierzbica Górna-Kołoczek",
  "Wierzbięcice",
  "Wierzbno",
  "Wierzchy-Niwy",
  "Wojsław",
  "Wojsławice",
  "Wołczyn",
  "Wydrowice",
  "Zabierzów",
  "Zalesie Śląskie",
  "Zawada",
  "Zawadzkie",
  "Zdzieszowice",
  "Zębowice",
  "Zimnice Małe",
  "Zwiastowice",
  "Żaba-Karolówka",
  "Żarów",
  "Żędowice",
  "Żywocice",
];

const cities_of_podkarpackie_province = [
  "Adamówka",
  "Albigowa",
  "Babica",
  "Bachórz",
  "Baranów Sandomierski",
  "Baryczka",
  "Bieliny",
  "Bieździadka",
  "Bieździedza",
  "Bircza",
  "Błażkowa",
  "Błażowa",
  "Błażowa Dolna",
  "Bobrowa",
  "Boguchwała",
  "Bojanów",
  "Bolestraszyce",
  "Borek Stary",
  "Borek Wielki",
  "Borowa",
  "Bratkowice",
  "Brzeziny",
  "Brzezówka",
  "Brzeźnica",
  "Brzozów",
  "Brzóza Królewska",
  "Brzyska",
  "Brzyska Wola",
  "Budy Głogowskie",
  "Budy Łańcuckie",
  "Bukowsko",
  "Cergowa",
  "Cewków",
  "Chmielnik",
  "Cholewiana Góra",
  "Chwałowice",
  "Cieklin",
  "Cieszanów",
  "Cieszyna",
  "Cmolas",
  "Cygany",
  "Czarna",
  "Czarna",
  "Czarna Sędziszowska",
  "Czaszyn",
  "Czermin",
  "Dachnów",
  "Dąbrowa",
  "Dąbrówki",
  "Dębica",
  "Dębno",
  "Dębowiec",
  "Dębów",
  "Długie",
  "Dobrzechów",
  "Domaradz",
  "Domatków",
  "Dukla",
  "Dulcza Wielka",
  "Dylągówka",
  "Dynów",
  "Dzikowiec",
  "Futoma",
  "Gać",
  "Giedlarowa",
  "Glinik",
  "Głogów Małopolski",
  "Głuchów",
  "Gniewczyna Łańcucka",
  "Gnojnica",
  "Godowa",
  "Gogołów",
  "Golcowa",
  "Gorzyce",
  "Góra Motyczna",
  "Górki",
  "Górno",
  "Grabownica Starzeńska",
  "Grodzisko",
  "Grodzisko Dolne",
  "Grodzisko Górne",
  "Gumniska",
  "Gwoźnica Górna",
  "Handzlówka",
  "Harta",
  "Hermanowa",
  "Horyniec-Zdrój",
  "Humniska",
  "Husów",
  "Huta Komorowska",
  "Hyżne",
  "Iskrzynia",
  "Iwierzyce",
  "Iwonicz",
  "Iwonicz-Zdrój",
  "Izdebki",
  "Jabłonica Polska",
  "Jadachy",
  "Jagiełła",
  "Jarocin",
  "Jarosław",
  "Jasienica Rosielna",
  "Jasionka",
  "Jasionka",
  "Jasionów",
  "Jasło",
  "Jastkowice",
  "Jaślany",
  "Jawornik",
  "Jawornik Polski",
  "Jedlicze",
  "Jelna",
  "Jeżowe",
  "Jodłowa",
  "Jodłówka",
  "Kalników",
  "Kamień",
  "Kańczuga",
  "Kąkolówka",
  "Kielnarowa",
  "Klęczany",
  "Klimkówka",
  "Kłyżów",
  "Kobylany",
  "Kolbuszowa",
  "Kolbuszowa Dolna",
  "Kolbuszowa Górna",
  "Kołaczyce",
  "Kombornia",
  "Komorów",
  "Konieczkowa",
  "Kopki",
  "Kopytowa",
  "Korczyna",
  "Kosina",
  "Kraczkowa",
  "Krasne",
  "Krosno",
  "Krościenko Wyżne",
  "Krzątka",
  "Krzemienica",
  "Krzywa",
  "Kupno",
  "Laszki",
  "Lesko",
  "Leżajsk",
  "Lipnica",
  "Lisie Jamy",
  "Lubaczów",
  "Lubatowa",
  "Lubenia",
  "Lubzina",
  "Lutcza",
  "Lutoryż",
  "Łańcut",
  "Łączki Brzeskie",
  "Łączki Kucharskie",
  "Łąka",
  "Łętownia",
  "Łężany",
  "Łopuszka Wielka",
  "Łowce",
  "Łowisko",
  "Łubno",
  "Łukawiec",
  "Łukawiec",
  "Majdan Sieniawski",
  "Malawa",
  "Malinówka",
  "Mała",
  "Medyka",
  "Medynia Głogowska",
  "Mielec",
  "Moderówka",
  "Mogielnica",
  "Morawsko",
  "Mrowla",
  "Munina",
  "Nagawczyna",
  "Nawsie",
  "Nawsie Kołaczyckie",
  "Niebieszczany",
  "Niebocko",
  "Niechobrz",
  "Niedźwiada",
  "Nienadowa",
  "Nienaszów",
  "Nisko",
  "Nowa Dęba",
  "Nowa Sarzyna",
  "Nowosielec",
  "Olchowa",
  "Olszanica",
  "Orły",
  "Orzechówka",
  "Osobnica",
  "Ostrów",
  "Pantalowice",
  "Parkosz",
  "Partynia",
  "Pilchów",
  "Pilzno",
  "Piwoda",
  "Podgrodzie",
  "Podleszany",
  "Pogwizdów",
  "Połomia",
  "Posada Górna",
  "Pruchnik",
  "Przemyśl",
  "Przeworsk",
  "Przędzel",
  "Pustynia",
  "Pustyny",
  "Racławice",
  "Racławówka",
  "Radomyśl Wielki",
  "Radymno",
  "Rakszawa",
  "Rogi",
  "Rogóżno",
  "Rokietnica",
  "Ropczyce",
  "Rozbórz",
  "Róża",
  "Ruda",
  "Ruda Różaniecka",
  "Rudna Mała",
  "Rudna Wielka",
  "Rudnik nad Sanem",
  "Rudołowice",
  "Rymanów-Zdrój",
  "Rzepedź",
  "Rzeszów",
  "Sanok",
  "Sędziszów Małopolski",
  "Siedleczka",
  "Sieniawa",
  "Sieniawa",
  "Sietesz",
  "Skołoszów",
  "Skołyszyn",
  "Sonina",
  "Sośnica",
  "Stale",
  "Stalowa Wola",
  "Stara Jastrząbka",
  "Stary Dzików",
  "Strachocina",
  "Strzyżów",
  "Surochów",
  "Świerzowa Polska",
  "Świlcza",
  "Targowiska",
  "Tarnobrzeg",
  "Tarnowiec",
  "Trzciana",
  "Trzciana",
  "Trzcinica",
  "Trzeboś",
  "Trzebuska",
  "Trześniów",
  "Trześń",
  "Trześń",
  "Tuczempy",
  "Turze Pole",
  "Tyczyn",
  "Ujkowice",
  "Ustrobna",
  "Ustrzyki Dolne",
  "Werynia",
  "Wierzawice",
  "Wola Rafałowska",
  "Wola Rusinowska",
  "Wola Zarczycka",
  "Wola Zgłobieńska",
  "Wólka Niedźwiedzka",
  "Wólka Pełkińska",
  "Wólka Podleśna",
  "Wrocanka",
  "Wydrza",
  "Wysoka Strzyżowska",
  "Wyszatyce",
  "Wyżne",
  "Zaborów",
  "Zaczernie",
  "Zagorzyce",
  "Zagórz",
  "Zahutyń",
  "Zaklików",
  "Zaleszany",
  "Zapałów",
  "Zarzecze",
  "Zawada",
  "Zgłobień",
  "Zmiennica",
  "Zwiernik",
  "Żeglce",
  "Żurawica",
  "Żurawiczki",
];

const cities_of_podlaskie_province = [
  "Achrymowce",
  "Adamowizna",
  "Adamowo",
  "Adamusy",
  "Agrafinówka",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrowo",
  "Aleksandrówka",
  "Aleksicze",
  "Aleksiejówka",
  "Ancuty",
  "Andrychy",
  "Andryjanki",
  "Andrzejewo",
  "Andrzejki",
  "Antonin",
  "Antonowo Kolonia",
  "Antosin",
  "Anusin",
  "Anusin",
  "Arbasy",
  "Ateny",
  "Augustowo",
  "Augustów",
  "Augustynka",
  "Aulakowszczyzna",
  "Babańce",
  "Babia Góra",
  "Babiki",
  "Babino",
  "Bachanowo",
  "Bachmatówka",
  "Bachury",
  "Baciki Bliższe",
  "Baciki Dalsze",
  "Baciuty",
  "Baciuty-Kolonia",
  "Bacze Mokre",
  "Bagienice",
  "Bagienice",
  "Bagienki",
  "Bagińskie",
  "Bagniuki",
  "Bagno",
  "Bajki-Zalesie",
  "Bakałarzewo",
  "Baliki",
  "Balinka",
  "Bańki",
  "Baranki",
  "Baranowce",
  "Baranowo",
  "Bargłów Dworny",
  "Bargłów Kościelny",
  "Bargłówka",
  "Barszcze",
  "Barszczewo",
  "Barszczewo",
  "Bartki",
  "Bartnia Góra",
  "Bartniki",
  "Barwiki",
  "Barzykowo",
  "Becejły",
  "Bełda",
  "Berżałowce",
  "Biała",
  "Biała Woda",
  "Białobłockie",
  "Białobrzegi",
  "Białobrzeskie",
  "Białogorce",
  "Białorogi",
  "Białorzeczka",
  "Białousy",
  "Białowieża",
  "Białystoczek",
  "Białystok",
  "Bielsk Podlaski",
  "Bienduszka",
  "Biszewo",
  "Bobinka",
  "Boćki",
  "Bojary",
  "Boksze Stare",
  "Bolesty",
  "Borek",
  "Borkowo",
  "Borowskie Olki",
  "Borowskie Skórki",
  "Borsukówka",
  "Borysowszczyzna",
  "Brańsk",
  "Bruszewo-Borkowizna",
  "Bryki",
  "Brześcianka",
  "Brzezina",
  "Brzeziny-Janowięta",
  "Brzozowo-Korabie",
  "Brzozowo-Solniki",
  "Brzóski Stare",
  "Brzóski-Falki",
  "Brzózki",
  "Buchwałowo",
  "Budziski",
  "Bujaki",
  "Bujny",
  "Burbiszki",
  "Charubiny",
  "Chmiele-Pogorzele",
  "Chmielewo",
  "Chojane-Gorczany",
  "Cholewy-Kołomyja",
  "Chomentowo",
  "Choroszcz",
  "Choszczewo",
  "Chranibory",
  "Cibory-Marki",
  "Ciechanowiec",
  "Cwaliny Duże",
  "Czarna Białostocka",
  "Czarna Wielka",
  "Czarnakowizna",
  "Czarnowo",
  "Czeremcha",
  "Czerwone",
  "Czerwone Bagno",
  "Czerwony Krzyż",
  "Czyżew",
  "Danówek",
  "Dąbrowa Białostocka",
  "Dąbrowa-Kaski",
  "Dąbrowa-Łazy",
  "Dębina",
  "Długie",
  "Dmochy-Mrozy",
  "Dobrzyniewo Duże",
  "Doliwy",
  "Dołęgi",
  "Dołubowo",
  "Domuraty",
  "Downary",
  "Drahle",
  "Dreństwo",
  "Drochlin",
  "Drohiczyn",
  "Drożęcin-Lubiejewo",
  "Dubicze Cerkiewne",
  "Dubicze Osoczne",
  "Dubno",
  "Duchny-Wieluny",
  "Dworaki-Staśki",
  "Dworzysk Kolonia",
  "Fasty",
  "Faszcze",
  "Filipów",
  "Franki-Dąbrowa",
  "Gałkówka",
  "Garbas Drugi",
  "Gawiny",
  "Gąsówka-Osse",
  "Giby",
  "Gielniewo",
  "Gliniski",
  "Głęboczek",
  "Godzieby",
  "Gołasze Mościckie",
  "Gołasze-Dąb",
  "Gołasze-Puszcza",
  "Goniądz",
  "Gorodczyno",
  "Gorszczyzna",
  "Gosie Małe",
  "Góra",
  "Górskie Ponikły-Stok",
  "Grabowo-Kolonie",
  "Grabowskie",
  "Grabówka",
  "Grajewo",
  "Granne",
  "Grauże Nowe",
  "Grauże Stare",
  "Gredele",
  "Grodziszczany",
  "Gródek",
  "Gródek",
  "Gródek-Kolonia",
  "Gruszki",
  "Grzebienie Kolonia",
  "Grzybowce",
  "Grzybowszczyzna",
  "Gugny",
  "Hajnówka",
  "Hanus",
  "Hodyszewo",
  "Hołny Wolmera",
  "Hołody",
  "Horodnianka",
  "Hoźna",
  "Huta",
  "Ignacewo",
  "Ignatówka",
  "Iwaniszki",
  "Jabłoń-Rykacze",
  "Jabłoń-Zambrowizna",
  "Jacowlany",
  "Jadeszki",
  "Jałówka",
  "Jamiołki-Piotrowięta",
  "Janki",
  "Jasionowo",
  "Jaświłki",
  "Jaworówka",
  "Jedwabne",
  "Juchnowiec Górny",
  "Juchnowiec Kościelny",
  "Kalinowo-Solki",
  "Kalinówka Królewska",
  "Kalnica",
  "Kałęczyn",
  "Kamień",
  "Kamień-Rupie",
  "Kapice Lipniki",
  "Karwowo",
  "Kazimierowo",
  "Kędziorowo",
  "Kielczany",
  "Kieljany",
  "Kisielnica",
  "Klejniki",
  "Kleosin",
  "Klepacze",
  "Kleszczele",
  "Klewinowo",
  "Klichy",
  "Kłyzówka",
  "Knyszewicze",
  "Knyszyn",
  "Kobyla",
  "Kobylin-Pogorzałki",
  "Kolno",
  "Kolonia Gródź",
  "Komosewo",
  "Kompocie",
  "Konopki",
  "Konopki-Jabłoń",
  "Koplany",
  "Korycin",
  "Koryciski",
  "Kosiorki",
  "Kossaki-Falki",
  "Kotówka",
  "Kozłowo",
  "Koźliki",
  "Krajewo-Borowe",
  "Krynki",
  "Kuźnica",
  "Lipsk",
  "Łapy",
  "Łomża",
  "Mały Płock",
  "Miastkowo",
  "Michałowo",
  "Mońki",
  "Narew",
  "Nowogród",
  "Nurzec-Stacja",
  "Piątnica Poduchowna",
  "Puńsk",
  "Raczki",
  "Radziłów",
  "Rajgród",
  "Rudka",
  "Rutki-Kossaki",
  "Sejny",
  "Siemiatycze",
  "Sobolewo",
  "Sokoły",
  "Sokółka",
  "Stare Kupiski",
  "Stawiski",
  "Suchowola",
  "Supraśl",
  "Suwałki",
  "Szczuczyn",
  "Szepietowo",
  "Sztabin",
  "Szumowo",
  "Śniadowo",
  "Tykocin",
  "Uhowo",
  "Wasilków",
  "Wąsosz",
  "Wizna",
  "Wysokie Mazowieckie",
  "Zabłudów",
  "Zambrów",
  "Zaścianki",
  "Zbójna",
];

const cities_of_pomorskie_province = [
  "Abisynia",
  "Abisynia Górska",
  "Adamki",
  "Albertowo",
  "Amalka",
  "Ameryka",
  "Ameryka",
  "Angowice",
  "Ankamaty",
  "Antoniewo",
  "Antoniewo Wybudowanie",
  "Antonin",
  "Asmus",
  "Babi Dół",
  "Babidół",
  "Babilon",
  "Babino",
  "Baby Leśniczówka",
  "Bachorze",
  "Bagna",
  "Bagniewo",
  "Balewko",
  "Balewo",
  "Bałachy",
  "Bałdowo",
  "Banino",
  "Baranowo",
  "Barchnowy",
  "Barcice",
  "Barcino",
  "Bargędzino",
  "Barkocin",
  "Barkowo",
  "Barlewice",
  "Barlewiczki",
  "Barłożno",
  "Barniewice",
  "Barnowiec",
  "Barnowo",
  "Bartel Mały",
  "Bartkowa Stajnia",
  "Bartoszylas",
  "Barwik",
  "Barwino",
  "Bawernica",
  "Bącka Huta",
  "Bącz-Olszowe Błoto",
  "Bączek-Zapowiednik",
  "Bądki",
  "Bągart",
  "Bąkowo",
  "Bekasowo",
  "Belfort",
  "Benowo",
  "Będominek",
  "Będziechowo",
  "Będzimierz",
  "Białachowo",
  "Białachówko",
  "Białe Błoto",
  "Białe Błoto",
  "Białogóra",
  "Biały Bukowiec",
  "Biebrowo",
  "Bielkowo",
  "Biesowiczki",
  "Błądzikowo",
  "Błotnia",
  "Bobowo",
  "Bobrowniki",
  "Bojano",
  "Bolesławowo",
  "Bolszewo",
  "Borkowo",
  "Borkowo",
  "Borzestowska Huta",
  "Borzyszkowy",
  "Bożepole Wielkie",
  "Bór",
  "Brda",
  "Brodnica Górna-Kalka",
  "Bronno",
  "Brudzewo",
  "Brusy",
  "Brzezie",
  "Brzeźno Lęborskie",
  "Brzeźno Szlacheckie",
  "Brzósk",
  "Brzyno",
  "Bukowo",
  "Bukówki",
  "Bychowo",
  "Bydgoszcz",
  "Bytów",
  "Cecenowo",
  "Cedry Małe",
  "Cedry Wielkie",
  "Cewice",
  "Chartowo",
  "Charzykowy",
  "Chełmek-Osada",
  "Chłapowo",
  "Chmielno",
  "Choczewo",
  "Chojna",
  "Chojnice",
  "Chotkowo",
  "Chwaszczyno",
  "Ciecholewy",
  "Ciechomice",
  "Ciemino",
  "Ciemno",
  "Cięgardło",
  "Cis",
  "Cisy ZR",
  "Czarlina Osada",
  "Czarna Dąbrówka",
  "Czarna Huta",
  "Czarna Woda",
  "Czarne",
  "Czarnocin",
  "Czarnówko",
  "Czarze",
  "Czatkowy",
  "Cząstkowo",
  "Czernin",
  "Czersk",
  "Człuchów",
  "Czyste",
  "Damnica",
  "Dargoleza",
  "Darżkowo",
  "Dąbrowa Brzezieńska",
  "Dąbrówka",
  "Debrzno",
  "Dębnica Kaszubska",
  "Dębogórze",
  "Donimierz",
  "Dretyń",
  "Drewniaczki",
  "Dudzicze",
  "Dunajki",
  "Dziechlino",
  "Dziemiany",
  "Dzierzgoń",
  "Dzierżążno",
  "Dzięgiel",
  "Egiertowo",
  "Frydrychowo",
  "Gałąźnia Mała",
  "Gałąźnia Wielka",
  "Gardeja",
  "Gąsiorki",
  "Gdańsk",
  "Gdynia",
  "Glincz",
  "Głodowo",
  "Główczyce",
  "Gniew",
  "Gniewino",
  "Gnieżdżewo",
  "Goręczyno",
  "Gostkowo",
  "Gościcino",
  "Gowidlino",
  "Gowino",
  "Grabowo Kościerskie",
  "Grzybno",
  "Hel",
  "Jastarnia",
  "Jastrzębia Góra",
  "Jezierzyce",
  "Juszkowo",
  "Kaliska",
  "Karsin",
  "Kartuzy",
  "Kębłowo",
  "Kępice",
  "Kielno",
  "Kiełpino",
  "Kleszczewo Kościerskie",
  "Kobylnica",
  "Koczała",
  "Kokoszkowy",
  "Kolbudy",
  "Koleczkowo",
  "Kołczygłowy",
  "Kościerzyna",
  "Kowale",
  "Krynica Morska",
  "Kwidzyn",
  "Leśniewo",
  "Leźno",
  "Lębork",
  "Lichnowy",
  "Linia",
  "Liniewo",
  "Lipusz",
  "Lisewo Malborskie",
  "Lubań",
  "Lubichowo",
  "Lublewo Gdańskie",
  "Luzino",
  "Łąg",
  "Łeba",
  "Łebcz",
  "Łebno",
  "Łęczyce",
  "Łęgowo",
  "Łubiana",
  "Malbork",
  "Mareza",
  "Miastko",
  "Miechucino",
  "Mikołajki Pomorskie",
  "Miłoradz",
  "Mosty",
  "Mosty",
  "Mrzezino",
  "Mściszewice",
  "Niestępowo",
  "Nowa Wieś Lęborska",
  "Nowy Dwór Gdański",
  "Nowy Staw",
  "Ogorzeliny",
  "Orle",
  "Parchowo",
  "Pelplin",
  "Pępowo",
  "Pinczyn",
  "Pogórze",
  "Połchowo",
  "Połczyno",
  "Potęgowo",
  "Prabuty",
  "Pruszcz Gdański",
  "Przechlewo",
  "Przodkowo",
  "Przyjaźń",
  "Przywidz",
  "Pszczółki",
  "Puck",
  "Rajkowy",
  "Rakowiec",
  "Reda",
  "Redzikowo",
  "Rekowo Górne",
  "Rotmanka",
  "Rumia",
  "Ryjewo",
  "Rytel",
  "Rzeczenica",
  "Sadlinki",
  "Siemianice",
  "Siemirowice",
  "Sierakowice",
  "Silno",
  "Skarszewy",
  "Skorzewo",
  "Skowarcz",
  "Skórcz",
  "Skrzeszewo",
  "Słupsk",
  "Smętowo Graniczne",
  "Sobowidz",
  "Somonino",
  "Sopot",
  "Stara Kiszewa",
  "Stare Pole",
  "Starogard Gdański",
  "Starzyno",
  "Stegna",
  "Stężyca",
  "Straszyn",
  "Strzebielino Osiedle",
  "Strzelno",
  "Subkowy",
  "Suchy Dąb",
  "Suchy Dwór",
  "Sulęczyno",
  "Swarożyn",
  "Swarzewo",
  "Sycewice",
  "Szemud",
  "Sztum",
  "Sztutowo",
  "Tczew",
  "Trąbki Wielkie",
  "Tuchomie",
  "Ustka",
  "Wejherowo",
  "Wiele",
  "Wielki Klincz",
  "Wierzchucino",
  "Wiślinka",
  "Władysławowo",
  "Zblewo",
  "Żelistrzewo",
  "Żukowo",
  "Żukowo-Wieś",
];

const cities_of_slaskie_province = [
  "Aleksandria Pierwsza",
  "Bażanowice",
  "Bąków",
  "Bełk",
  "Bełsznica",
  "Bestwina",
  "Bestwinka",
  "Będzin",
  "Biała",
  "Bielsko-Biała",
  "Bieńkowice",
  "Bieruń",
  "Biery",
  "Blachownia",
  "Bobrowniki",
  "Bojszowy",
  "Bojszowy Nowe",
  "Boronów",
  "Borowe",
  "Borucin",
  "Brenna",
  "Bronów",
  "Brudzowice",
  "Brzeźce",
  "Brzuśnik",
  "Buczkowice",
  "Bujaków",
  "Bystra",
  "Bytom",
  "Chałupki",
  "Chełm Śląski",
  "Choroń",
  "Chorzów",
  "Chruszczobród",
  "Chudów",
  "Cieszyn",
  "Cisiec",
  "Cisownica",
  "Cynków",
  "Czaniec",
  "Czechowice-Dziedzice",
  "Czeladź",
  "Czernica",
  "Czernichów",
  "Czerwionka-Leszczyny",
  "Częstochowa",
  "Czyżowice",
  "Ćwiklice",
  "Dankowice",
  "Dąbrowa Górnicza",
  "Dębowiec",
  "Drogomyśl",
  "Frydek",
  "Gaszowice",
  "Gierałtowice",
  "Gilowice",
  "Gliwice",
  "Goczałkowice-Zdrój",
  "Godziszka",
  "Gogołowa",
  "Golasowice",
  "Goleszów",
  "Gorzyce",
  "Gorzyczki",
  "Gostyń",
  "Górki Wielkie",
  "Hażlach",
  "Hecznarowice",
  "Herby",
  "Huta Stara B",
  "Iłownica",
  "Imielin",
  "Istebna",
  "Jankowice",
  "Jankowice",
  "Janowice",
  "Jasienica",
  "Jastrząb",
  "Jastrzębie-Zdrój",
  "Jaworze",
  "Jaworzno",
  "Jaworzynka",
  "Jejkowice",
  "Jeleśnia",
  "Juszczyna",
  "Kalety",
  "Kamesznica",
  "Kamienica Polska",
  "Kamyk",
  "Kaniów",
  "Katowice",
  "Kiczyce",
  "Kłobuck",
  "Kłomnice",
  "Knurów",
  "Kobielice",
  "Kobiernice",
  "Kobiór",
  "Kobyla",
  "Kochanowice",
  "Koniaków",
  "Koniecpol",
  "Konopiska",
  "Kończyce Wielkie",
  "Korbielów",
  "Koszarawa",
  "Koszęcin",
  "Kościelec",
  "Kotulin",
  "Koziegłowy",
  "Kozłów",
  "Kozy",
  "Kroczyce",
  "Krostoszowice",
  "Krupski Młyn",
  "Krzanowice",
  "Krzyżowa",
  "Książenice",
  "Kusięta",
  "Kuźnia Raciborska",
  "Lelów",
  "Leśna",
  "Lędziny",
  "Ligota",
  "Lipie",
  "Lipowa",
  "Lubliniec",
  "Lubomia",
  "Łaziska Górne",
  "Łazy",
  "Łąka",
  "Łękawica",
  "Łobodno",
  "Łodygowice",
  "Łojki",
  "Marklowice",
  "Mazańcowice",
  "Miasteczko Śląskie",
  "Miedary",
  "Miedźna",
  "Miedźno",
  "Mierzęcice",
  "Międzybrodzie Bialskie",
  "Międzybrodzie Żywieckie",
  "Międzyrzecze Dolne",
  "Międzyrzecze Górne",
  "Międzyświeć",
  "Mikołów",
  "Milówka",
  "Mizerów",
  "Mnich",
  "Mszana",
  "Mykanów",
  "Mysłowice",
  "Myszków",
  "Nędza",
  "Niegowonice",
  "Nieledwia",
  "Nierada",
  "Nowe Chechło",
  "Ochaby Małe",
  "Olsztyn",
  "Olza",
  "Opatów",
  "Ornontowice",
  "Orzech",
  "Orzesze",
  "Ożarowice",
  "Paczyna",
  "Paniówki",
  "Panki",
  "Pawłowice",
  "Pawonków",
  "Pewel Mała",
  "Pewel Ślemieńska",
  "Pewel Wielka",
  "Piasek",
  "Piekary Śląskie",
  "Pielgrzymowice",
  "Pierściec",
  "Pietrowice Wielkie",
  "Pilchowice",
  "Pilica",
  "Pisarzowice",
  "Pogrzebień",
  "Pogwizdów",
  "Połomia",
  "Poraj",
  "Porąbka",
  "Poręba",
  "Pruchna",
  "Przegędza",
  "Przyrów",
  "Przystajń",
  "Przyszowice",
  "Pszczyna",
  "Pszów",
  "Pyskowice",
  "Racibórz",
  "Radlin",
  "Radostowice",
  "Radziechowy",
  "Radzionków",
  "Rajcza",
  "Raszczyce",
  "Rędziny",
  "Rogoźnik",
  "Rogów",
  "Ruda Śląska",
  "Rudniki",
  "Rudniki",
  "Rudno",
  "Rudzica",
  "Rudziniec",
  "Rusinowice",
  "Rybarzowice",
  "Rybnik",
  "Rycerka Dolna",
  "Rychwałd",
  "Rydułtowy",
  "Rzerzęczyce",
  "Rzuchów",
  "Sączów",
  "Siemianowice Śląskie",
  "Sierakowice",
  "Siewierz",
  "Skoczów",
  "Skrzyszów",
  "Sławków",
  "Sopotnia Mała",
  "Sopotnia Wielka",
  "Sosnowiec",
  "Sośnicowice",
  "Sól",
  "Stanowice",
  "Stara Wieś",
  "Starcza",
  "Strzebiń",
  "Strzyżowice",
  "Studzienice",
  "Studzionka",
  "Syrynia",
  "Szczejkowice",
  "Szczekociny",
  "Szczerbice",
  "Szczyrk",
  "Ślemień",
  "Świbie",
  "Świerczyniec",
  "Świerklany",
  "Świętochłowice",
  "Świnna",
  "Tarnowskie Góry",
  "Tąpkowice",
  "Toszek",
  "Truskolasy",
  "Trzebinia",
  "Turza Śląska",
  "Twardorzeczka",
  "Tworków",
  "Tworóg",
  "Tychy",
  "Ustroń",
  "Warszowice",
  "Widzów",
  "Wielowieś",
  "Wieszowa",
  "Wilamowice",
  "Wilcza",
  "Wilkowice",
  "Wisła",
  "Wisła Mała",
  "Wisła Wielka",
  "Włodowice",
  "Wodzisław Śląski",
  "Wojkowice",
  "Wojkowice Kościelne",
  "Wola",
  "Woźniki",
  "Wrzosowa",
  "Wyry",
  "Wysoka",
  "Zabłocie",
  "Zaborze",
  "Zabrze",
  "Zabrzeg",
  "Zamarski",
  "Zarzecze",
  "Zawiercie",
  "Zebrzydowice",
  "Złochowice",
  "Złoty Potok",
  "Zwonowice",
  "Żabnica",
  "Żarki",
  "Żarki Letnisko",
  "Żelisławice",
  "Żernica",
  "Żory",
  "Żywiec",
];

const cities_of_swietokrzyskie_province = [
  "Adamczowice",
  "Adamek",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adamów",
  "Adelinów",
  "Akwizgran",
  "Aleksandrów",
  "Aleksandrów",
  "Ambrożów",
  "Andruszkowice",
  "Antonielów",
  "Antoniów",
  "Baczyna",
  "Baćkowice",
  "Balice",
  "Bałków",
  "Bałtów",
  "Baran",
  "Baranów",
  "Baranów",
  "Baranówek",
  "Barcza",
  "Barcza",
  "Bartoszowiny",
  "Barycz",
  "Barycz",
  "Baszowice",
  "Bazów",
  "Bebelno Kolonia",
  "Bebelno Wieś",
  "Bedlenko",
  "Bedlno",
  "Bejsce",
  "Bełzów",
  "Beradz",
  "Bernów",
  "Beszowa",
  "Beszyce",
  "Bębnów",
  "Bęczków",
  "Białoborze",
  "Białowieża",
  "Biały Ług",
  "Bidziny",
  "Bidzińszczyzna",
  "Biedrzykowice",
  "Bieliny",
  "Bilcza",
  "Biskupice",
  "Bliżyn",
  "Bodzechów",
  "Bodzentyn",
  "Bogoria",
  "Bogucice I Zakościele",
  "Bogucice II Zakamień",
  "Borek",
  "Borzykowa",
  "Bożydar",
  "Brody",
  "Brody",
  "Brzechów",
  "Brzeście",
  "Brzeście",
  "Brzezie",
  "Brzezinki",
  "Brzeziny",
  "Brzeźnica",
  "Buczek",
  "Budy-Jakubowice",
  "Bugaj",
  "Bugaj",
  "Bukowa",
  "Busko-Zdrój",
  "Byczów",
  "Bydłowa",
  "Byszówka",
  "Cedzyna",
  "Chałupki",
  "Charężów",
  "Chełmce",
  "Chęciny",
  "Chinków",
  "Chmielnik",
  "Chorzewa",
  "Chroberz",
  "Chwałki",
  "Chwałowice",
  "Chwaścice",
  "Chyby",
  "Czałczyn",
  "Czarnca Wymysłów",
  "Czarniecka Góra",
  "Czartoszowy",
  "Czażów",
  "Czekaj",
  "Czepiec",
  "Czerników Karski",
  "Czyżów Szlachecki",
  "Ćmielów",
  "Ćmińsk Kościelny-Podgród",
  "Ćmińsk Rządowy-Światełek",
  "Ćmińsk Rządowy-Wyręba",
  "Dacharzów",
  "Daleszyce",
  "Dąbrowa",
  "Dębiany",
  "Dmosice",
  "Domaszowice",
  "Drutarnia",
  "Dwikozy",
  "Dyminy",
  "Działoszyce",
  "Dziurów",
  "Elżbiecin",
  "Ewelinów",
  "Ewelinów Fryszerka",
  "Fałków",
  "Gabułtów",
  "Gadka",
  "Gluzy",
  "Gorysławice",
  "Gowarczów",
  "Górki",
  "Górno",
  "Górno-Zawada",
  "Górny Młyn",
  "Góry Lasochowskie",
  "Góry Sieradzkie",
  "Grabki Małe",
  "Gródek",
  "Grzybowa Góra",
  "Grzymała",
  "Holendry",
  "Huta Nowa",
  "Huta Stara",
  "Huta Szklana",
  "Iwaniska",
  "Jacentów",
  "Jakimowice Kolonia",
  "Jakubów",
  "Jamskie",
  "Janik",
  "Janów",
  "Jaworznia",
  "Jędrzejowice",
  "Jędrzejów",
  "Jęgrzna",
  "Józefów Witowicki",
  "Judasze",
  "Jurkowice",
  "Kakonin",
  "Kamienna Góra",
  "Kamieńczyce",
  "Kamyszów",
  "Karczunek",
  "Kawęczyn",
  "Kazimierza Wielka",
  "Kielce",
  "Kierz Niedźwiedzi",
  "Kików",
  "Klępie Dolne",
  "Klimontów",
  "Kłoda Kolonia",
  "Kłucko",
  "Kobiela",
  "Kolonia Piaski",
  "Kolosy",
  "Komorów",
  "Komparzów",
  "Konieczno",
  "Końskie",
  "Koprzywnica",
  "Kornacice",
  "Korytnica",
  "Korzenno",
  "Kostomłoty Drugie",
  "Kostomłoty Pierwsze",
  "Kowala Mała",
  "Krasocin",
  "Krężołek",
  "Krynki",
  "Krzczonów",
  "Krzyszkowice",
  "Krzyżanowice Średnie",
  "Kunów",
  "Kurzacze",
  "Kurzelów",
  "Kuźniaki",
  "Kwaszyn",
  "Las Winiarski",
  "Lechów",
  "Leszczyny",
  "Lipa",
  "Lipia Góra",
  "Lipno",
  "Lipowe Pole Plebańskie",
  "Lipy",
  "Lubienia",
  "Ludwinów",
  "Łagów",
  "Łatanice",
  "Łążek",
  "Łoniów-Kolonia",
  "Łopuszno",
  "Łosień",
  "Łukowa",
  "Łysaków Drugi",
  "Maksymów",
  "Maleniec",
  "Malice Kościelne",
  "Malżyn",
  "Małogoszcz",
  "Małoszyce",
  "Marcinkowice",
  "Masłów Drugi",
  "Masłów Pierwszy",
  "Mąchocice Kapitulne",
  "Michala Góra",
  "Michałów",
  "Micigózd",
  "Miedziana Góra",
  "Miedzierza",
  "Mikułowice",
  "Milejowice",
  "Mirzec Stary",
  "Mirzec-Korzonek",
  "Młynek",
  "Mnin Szwedy",
  "Mniów",
  "Modliszewice",
  "Mokrsko Górne",
  "Momocicha",
  "Morawica",
  "Mościska Małe",
  "Mójcza",
  "Mściów",
  "Nadolnik",
  "Nalewajków",
  "Niestachów",
  "Nieświń",
  "Nowa Słupia",
  "Nowiny",
  "Nowy Korczyn",
  "Oblęgorek",
  "Oleszno",
  "Oleśnica",
  "Opatów",
  "Osiek",
  "Ostrowiec Świętokrzyski",
  "Ożarów",
  "Pacanów",
  "Parszów",
  "Pawłów",
  "Piekoszów",
  "Pierzchnica",
  "Pińczów",
  "Pliskowola",
  "Połaniec",
  "Promnik",
  "Radlin",
  "Radoszyce",
  "Raków",
  "Rogów",
  "Rudki",
  "Rykoszyn",
  "Rytwiany",
  "Sandomierz",
  "Secemin",
  "Sędziszów",
  "Skalbmierz",
  "Skarżysko Kościelne",
  "Skarżysko-Kamienna",
  "Skorzeszyce",
  "Starachowice",
  "Staszów",
  "Stąporków",
  "Stopnica",
  "Strawczyn",
  "Strawczynek",
  "Suchedniów",
  "Suchowola",
  "Suków",
  "Szewna",
  "Szydłów",
  "Tokarnia",
  "Topola",
  "Wąchock",
  "Wielka Wieś",
  "Włostów",
  "Włoszczowa",
  "Wodzisław",
  "Wola Jachowa",
  "Wola Kopcowa",
  "Wolica",
  "Zagnańsk",
  "Zawichost",
  "Zbludowice",
  "Zgórsko",
];

const cities_of_warminsko_mazurskie_province = [
  "Adamowo",
  "Adamowo-Osiedle",
  "Aleksandrowo",
  "Ameryka",
  "Anglity",
  "Aniołowo",
  "Antomieszki",
  "Antonia",
  "Antoniewo",
  "Antonowo",
  "Anuszewo",
  "Aptynty",
  "Ardapy",
  "Arklity",
  "Asuny",
  "Audyniszki",
  "Augamy",
  "Augustowo",
  "Awajki",
  "Babiak",
  "Babięta",
  "Babięty Małe",
  "Babki",
  "Babki Gąseckie",
  "Babki Oleckie",
  "Babrosty",
  "Bachorza",
  "Bagienice",
  "Bagieńsko",
  "Bagnity",
  "Bagno",
  "Bajdy",
  "Bajdyty",
  "Bajorski Gaj",
  "Bajory Małe",
  "Bajory Wielkie",
  "Bajtkowo",
  "Balewo",
  "Bałamutowo",
  "Bałąg",
  "Bałdy",
  "Bałdzki Piec",
  "Bałoszyce",
  "Bałoszyce Małe",
  "Bałowo",
  "Bałowo",
  "Bałtrucie",
  "Bałupiany",
  "Banaszki",
  "Banie Mazurskie",
  "Baranowo",
  "Baranówka Leśniczówka",
  "Barany",
  "Barany",
  "Barciany",
  "Barcie",
  "Barcikowo",
  "Barciszewo",
  "Barczewko",
  "Barczewo",
  "Barczewski Dwór",
  "Bardyny",
  "Bark",
  "Bartąg",
  "Bartążek",
  "Bartężek",
  "Bartki",
  "Bartki",
  "Bartkowski Dwór",
  "Bartołty Małe",
  "Bartołty Wielkie",
  "Bartosze",
  "Bartoszki",
  "Bartoszyce",
  "Barty",
  "Barwiny",
  "Batorowo",
  "Bażyny",
  "Bądle",
  "Bądy",
  "Bądze",
  "Bełk",
  "Bemowizna",
  "Bemowo Piskie",
  "Berkowo",
  "Bezledy",
  "Biała Góra",
  "Biała Olecka",
  "Biała Piska",
  "Biała Wola",
  "Białczyn",
  "Białe Jeziorki",
  "Białka",
  "Białka",
  "Białuty",
  "Biały Grunt",
  "Biedaszki Małe",
  "Biskupiec",
  "Biskupiec",
  "Biskupiec-Kolonia Trzecia",
  "Bisztynek",
  "Bobry",
  "Boczki",
  "Boćwinka",
  "Bogdany",
  "Boleszyn",
  "Borki",
  "Boryty",
  "Borzymy",
  "Borzynowo",
  "Boże Małe",
  "Braniewo",
  "Bratian",
  "Bredynki",
  "Bronisze",
  "Bronowo",
  "Brożówka",
  "Brusiny",
  "Brusiny Małe",
  "Bryńsk",
  "Brzozowo",
  "Budziska",
  "Bursz",
  "Butowo",
  "Canki",
  "Cegielnia",
  "Cegłowo",
  "Chełchy",
  "Chełmiec",
  "Choszczewo",
  "Cichogrąd",
  "Ciemna Dąbrowa",
  "Cwalinki",
  "Czarny Róg",
  "Czechowo",
  "Czerlin",
  "Czerniki",
  "Czerwona Woda",
  "Czosnowo",
  "Dąb",
  "Dąbrowa",
  "Dąbrowskie",
  "Dąbrowskie Os.",
  "Dąbrowy",
  "Dąbrówka Mała",
  "Dąbrówno",
  "Dęby",
  "Długobór",
  "Długosze",
  "Doba",
  "Dobre Miasto",
  "Dobrocin",
  "Dobrzyń",
  "Drozdowo",
  "Drulity",
  "Drwęca",
  "Drygały",
  "Drzazgi",
  "Dudka",
  "Dudki",
  "Dwórzno",
  "Dymer",
  "Dywity",
  "Dziaduszyn",
  "Działdowo",
  "Dzietrzychowo",
  "Dzięgiele Oleckie",
  "Dzikowina",
  "Dziubiele",
  "Dziurdziewo",
  "Dźwierzuty",
  "Elbląg",
  "Elganowo",
  "Elgnowo",
  "Ełk",
  "Falknowo",
  "Fitowo",
  "Fiugajki",
  "Franciszkowo",
  "Frombork",
  "Garbno",
  "Gardyny",
  "Gęsie Góry",
  "Gieduty",
  "Giełpsz",
  "Giżycko",
  "Glądy",
  "Ględy",
  "Glinki",
  "Gładysze",
  "Głąbowo",
  "Głogno",
  "Głuch",
  "Godkowo",
  "Golubie Wężewskie",
  "Golubki",
  "Gołąbki",
  "Gołdap",
  "Goryń",
  "Górowo Iławeckie",
  "Grabacz",
  "Grabnik",
  "Grabno",
  "Gralewo-Stacja",
  "Grazymy",
  "Grądzkie Ełckie",
  "Gronowo",
  "Gronowo",
  "Gronowo Elbląskie",
  "Gronowo Górne",
  "Gruda",
  "Grunajki",
  "Gryżewo",
  "Grzybowo",
  "Gulbity",
  "Gutkowo",
  "Guty",
  "Guzki",
  "Iława",
  "Iłowo-Osada",
  "Jabłonka",
  "Jachimówka",
  "Jagarzewo",
  "Jagodziny",
  "Jamielnik",
  "Janiki Wielkie",
  "Jedwabno",
  "Jegłownik",
  "Jeziorany",
  "Jonkowo",
  "Kajkowo",
  "Kętrzyn",
  "Kieźliny",
  "Kisielice",
  "Korsze",
  "Kowale Oleckie",
  "Kozłowo",
  "Kruklanki",
  "Kurzętnik",
  "Lidzbark",
  "Lidzbark Warmiński",
  "Lubawa",
  "Lubomino",
  "Łęgajny",
  "Łukta",
  "Małdyty",
  "Mikołajki",
  "Miłakowo",
  "Miłomłyn",
  "Młynary",
  "Morąg",
  "Mrągowo",
  "Mroczno",
  "Narzym",
  "Nidzica",
  "Nowa Wieś Ełcka",
  "Nowe Miasto Lubawskie",
  "Olecko",
  "Olsztyn",
  "Olsztynek",
  "Orneta",
  "Orzysz",
  "Ostróda",
  "Pasłęk",
  "Pasym",
  "Piecki",
  "Pieniężno",
  "Pisanica",
  "Pisz",
  "Płośnica",
  "Pozezdrze",
  "Prostki",
  "Reszel",
  "Rozogi",
  "Różnowo",
  "Ruciane-Nida",
  "Rybno",
  "Ryn",
  "Samborowo",
  "Sępopol",
  "Spychowo",
  "Srokowo",
  "Stare Juchy",
  "Stawiguda",
  "Straduny",
  "Susz",
  "Szczytno",
  "Świętajno",
  "Tolkmicko",
  "Węgorzewo",
  "Wielbark",
  "Wilkasy",
  "Wójtowo",
  "Wydminy",
  "Zalewo",
  "Ząbrowo",
  "Żabi Róg",
];

const cities_of_wielkopolskie_province = [
  "Babiak",
  "Baranowo",
  "Baranów",
  "Biadki",
  "Biała",
  "Białośliwie",
  "Biedrusko",
  "Bielsko",
  "Biskupice Ołoboczne",
  "Bogucin",
  "Bojanowo",
  "Bolechowo Osiedle",
  "Bolewice",
  "Borek Wielkopolski",
  "Borówiec",
  "Boruja Kościelna",
  "Bralin",
  "Brenno",
  "Broniszewice",
  "Brudzew",
  "Brzeźno",
  "Budzisław Kościelny",
  "Budzyń",
  "Buk",
  "Bukowiec",
  "Bukówiec Górny",
  "Chludowo",
  "Chobienice",
  "Chocicza",
  "Chodzież",
  "Chrzan",
  "Ciążeń",
  "Cielcza",
  "Cisew",
  "Czacz",
  "Czapury",
  "Czarnków",
  "Czarnylas",
  "Czempiń",
  "Czerniejewo",
  "Czerwonak",
  "Damasławek",
  "Daszewice",
  "Dąbcze",
  "Dąbie",
  "Dąbrowa",
  "Dąbrówka",
  "Dębnica",
  "Dobieżyn",
  "Dobra",
  "Dolsk",
  "Dopiewo",
  "Doruchów",
  "Drawski Młyn",
  "Drawsko",
  "Duszniki",
  "Gałowo",
  "Garzyn",
  "Gniezno",
  "Golina",
  "Golina",
  "Gołańcz",
  "Gołaszyn",
  "Gołuchów",
  "Gostyń",
  "Grabów nad Prosną",
  "Granowiec",
  "Granowo",
  "Grodziec",
  "Grodzisk Wielkopolski",
  "Gruszczyn",
  "Grzegorzew",
  "Gułtowy",
  "Hanulin",
  "Jarocin",
  "Jasin",
  "Jastrowie",
  "Jerka",
  "Jerzykowo",
  "Jutrosin",
  "Kaczory",
  "Kalisz",
  "Kamieniec",
  "Kamionki",
  "Karpicko",
  "Kaszczor",
  "Kazimierz Biskupi",
  "Kaźmierz",
  "Kąkolewo",
  "Kębłowo",
  "Kępno",
  "Kicin",
  "Kiekrz",
  "Kiełczewo",
  "Kiszkowo",
  "Kleczew",
  "Kłecko",
  "Kłoda",
  "Kłodawa",
  "Kobyla Góra",
  "Kobylin",
  "Kobylnica",
  "Koło",
  "Komorniki",
  "Konary",
  "Konin",
  "Kostrzyn",
  "Kościan",
  "Kościelna Wieś",
  "Kotlin",
  "Kowalew",
  "Kowanówko",
  "Koziegłowy",
  "Koźmin Wielkopolski",
  "Koźminek",
  "Kórnik",
  "Krajenka",
  "Kramsk",
  "Kraszewice A",
  "Krobia",
  "Krosno",
  "Krotoszyn",
  "Krzemieniewo",
  "Krzywiń",
  "Krzyż Wielkopolski",
  "Książ Wielkopolski",
  "Kuźnica Czarnkowska",
  "Kwilcz",
  "Laski",
  "Leszno",
  "Lewków",
  "Licheń Stary",
  "Lipka",
  "Lipno",
  "Lisków",
  "Lotyń",
  "Lubasz",
  "Luboń",
  "Lusowo",
  "Łobżenica",
  "Malanów",
  "Margonin",
  "Masłowo",
  "Miasteczko Krajeńskie",
  "Mieszków",
  "Mieścisko",
  "Międzychód",
  "Miłosław",
  "Mochy",
  "Mosina",
  "Mroczeń",
  "Murowana Goślina",
  "Nekla",
  "Niechanowo",
  "Niepruszewo",
  "Nochowo",
  "Nowa Wieś",
  "Nowe Miasto nad Wartą",
  "Nowe Skalmierzyce",
  "Nowy Tomyśl",
  "Oborniki",
  "Obra",
  "Obrzycko",
  "Odolanów",
  "Okonek",
  "Olszowa",
  "Olszyna",
  "Opalenica",
  "Opatów",
  "Opatówek",
  "Orchowo",
  "Orzechowo",
  "Osiek nad Notecią",
  "Ostroróg",
  "Ostrów Wielkopolski",
  "Ostrzeszów",
  "Otorowo",
  "Owińska",
  "Pakosław",
  "Pamiątkowo",
  "Parkowo",
  "Pawłowice",
  "Pecna",
  "Pęckowo",
  "Pępowo",
  "Piaski",
  "Pięczkowo",
  "Piła",
  "Pleszew",
  "Plewiska",
  "Pniewy",
  "Pobiedziska",
  "Połajewo",
  "Poniec",
  "Posada",
  "Powidz",
  "Poznań",
  "Przedecz",
  "Przemęt",
  "Przeźmierowo",
  "Przygodzice",
  "Psarskie",
  "Pudliszki",
  "Puszczykowo",
  "Pyzdry",
  "Raczyce",
  "Radłów",
  "Rakoniewice",
  "Raszków",
  "Rawicz",
  "Robakowo",
  "Rogalinek",
  "Rogoźno",
  "Rokietnica",
  "Rosko",
  "Rostarzewo",
  "Rozdrażew",
  "Rożnowo",
  "Rychtal",
  "Rychwał",
  "Ryczywół",
  "Rydzyna",
  "Siedlec",
  "Siedlików",
  "Sierakowo",
  "Sieraków",
  "Sieroszewice",
  "Skoki",
  "Skórzewo",
  "Skulsk",
  "Sławsk",
  "Słupca",
  "Smolice",
  "Sompolno",
  "Sośnie",
  "Stara Łubianka",
  "Stare Bojanowo",
  "Stare Miasto",
  "Stary Widzim",
  "Stawiszyn",
  "Stęszew",
  "Strykowo",
  "Strzałkowo",
  "Strzyżew",
  "Suchy Las",
  "Sulęcinek",
  "Swarzędz",
  "Sypniewo",
  "Szamotuły",
  "Ślesin",
  "Śmigiel",
  "Śrem",
  "Środa Wielkopolska",
  "Świba",
  "Święciechowa",
  "Świętno",
  "Taczanów Drugi",
  "Tarchały Wielkie",
  "Tarnowo Podgórne",
  "Tarnówka",
  "Topola Mała",
  "Trzcianka",
  "Trzemeszno",
  "Tuchorza",
  "Tulce",
  "Tuliszków",
  "Turek",
  "Uciechów",
  "Ujście",
  "Wapno",
  "Wągrowiec",
  "Wąsowo",
  "Wieleń",
  "Wielichowo",
  "Wielowieś",
  "Wilczogóra",
  "Wilkowice",
  "Wilkowyja",
  "Wiry",
  "Witaszyce",
  "Witkowo",
  "Wojnowice",
  "Wolsztyn",
  "Wronki",
  "Września",
  "Wtórek",
  "Wyrzysk",
  "Wysocko Małe",
  "Wysocko Wielkie",
  "Wysoka",
  "Zagórów",
  "Zakrzewo",
  "Zalasewo",
  "Zaniemyśl",
  "Zbąszyń",
  "Zbiersk-Cukrownia",
  "Zduny",
  "Złotów",
  "Żychlin",
  "Żydowo",
];

const cities_of_zachodniopomorskie_province = [
  "Anielino",
  "Antoniewice",
  "Antoniewko",
  "Babigoszcz",
  "Babin",
  "Babin",
  "Babinek",
  "Babinek",
  "Baczyn",
  "Baczysław",
  "Bagicz",
  "Bagna",
  "Bagno",
  "Banie",
  "Baniewice",
  "Bara",
  "Bardzlino",
  "Barlinek",
  "Barnim",
  "Barnimie",
  "Barnin",
  "Barnisławice",
  "Barnówko",
  "Bartkowo",
  "Bartlewo",
  "Bartoszewo",
  "Barwice",
  "Barzkowice",
  "Barzowice",
  "Baszewice",
  "Batowo",
  "Batyń",
  "Bącznik",
  "Bądki",
  "Bądkowo",
  "Bedlno",
  "Bełczna",
  "Bełtno",
  "Berkanowo",
  "Bezrzecze",
  "Będzin",
  "Biała",
  "Biała Kępa",
  "Białe",
  "Białęcino",
  "Białęgi",
  "Białogard",
  "Białogórzynko",
  "Białogórzyno",
  "Białuń",
  "Białuń",
  "Biały Bór",
  "Biały Zdrój",
  "Bieczynko",
  "Bielice",
  "Bienice",
  "Bierzwnik",
  "Biesiekierz",
  "Binowo",
  "Biskupice",
  "Blizno",
  "Błotno",
  "Bobolice",
  "Bogucino",
  "Boguszyce",
  "Boguszyny",
  "Bolesławice",
  "Boleszkowice",
  "Boleszkowice",
  "Bonin",
  "Borne Sulinowo",
  "Borzęcin",
  "Brojce",
  "Bronowo",
  "Brzękowice",
  "Brzozowo",
  "Brzozowo",
  "Buczek",
  "Budzień",
  "Buk",
  "Buszęcin",
  "Buślarki",
  "Cedynia",
  "Cerkwica",
  "Cetuń",
  "Chełm Dolny",
  "Chełm Górny",
  "Chełm Gryficki",
  "Chlebowo",
  "Chlewice",
  "Chłopska Kępa",
  "Chociwel",
  "Chojna",
  "Choszczno",
  "Chudaczewo",
  "Chwiram",
  "Cieszyno",
  "Ciosna",
  "Cisewo",
  "Czachów",
  "Czaplinek",
  "Czarnowęsy",
  "Człopa",
  "Czółnów",
  "Daleszewo",
  "Dalno",
  "Danowo",
  "Dargosław",
  "Darłowo",
  "Darskowo",
  "Darzowice",
  "Dąbie",
  "Dąbrowica",
  "Dąbrówka",
  "Dębica",
  "Dębno",
  "Dębołęka",
  "Dębostrów",
  "Dębowo",
  "Dłusko",
  "Dobiesław",
  "Dobino",
  "Dobra",
  "Dobra",
  "Dobre",
  "Dobre Małe",
  "Dobropole Gryfińskie",
  "Dobroszyn",
  "Dobrzany",
  "Dolice",
  "Dolsko",
  "Dołgie",
  "Dołgie",
  "Dominikowo",
  "Drawno",
  "Drawsko Pomorskie",
  "Drozdowo",
  "Drzeńsko",
  "Drzesz",
  "Dusin",
  "Dygowo",
  "Dyminek",
  "Dzieszkowo",
  "Dziki",
  "Dzikowo",
  "Dziwnów",
  "Dziwnówek",
  "Gardno",
  "Gardziec",
  "Gądno",
  "Gąsierzyno",
  "Giżyn",
  "Glicko",
  "Gliniec",
  "Głazów",
  "Głowaczewo",
  "Gocławice",
  "Godków",
  "Golczewo",
  "Goleniów",
  "Golice",
  "Gosław",
  "Gostyński Bród",
  "Gościno",
  "Gościno Dwór",
  "Gozd",
  "Górnowo",
  "Górsko",
  "Gracz",
  "Grąbczewo",
  "Grochów",
  "Gromnik",
  "Gruszewo",
  "Gryfice",
  "Gryfino",
  "Grzędzice",
  "Grzmiąca",
  "Grzybowo",
  "Gwizd",
  "Ińsko",
  "Iwięcino",
  "Jacinki",
  "Jadwiżyn",
  "Jagniątkowo",
  "Jarosławiec",
  "Jarosławki",
  "Jarzysław",
  "Jatki",
  "Jazy",
  "Jaźwiny",
  "Jelonki",
  "Jezierzany",
  "Jezierzyce",
  "Jęczydół",
  "Kalinówka",
  "Kalisz Pomorski",
  "Kamień Pomorski",
  "Karkowo",
  "Karlino",
  "Karpin",
  "Karsko",
  "Kazimierz",
  "Kądzielno",
  "Kępica",
  "Kępiny",
  "Kępka",
  "Kępno",
  "Kierzkowo",
  "Kinowo",
  "Klasztorne",
  "Klępicz",
  "Kliniska Wielkie",
  "Kłanino",
  "Kłębowiec",
  "Kłodkowo",
  "Kłodzino",
  "Knieja",
  "Kobylanka",
  "Kocierz",
  "Kodrąbek",
  "Kolno",
  "Kolno",
  "Kolonia IV Chłopowo",
  "Kołbacz",
  "Kołobrzeg",
  "Komorniki",
  "Komorowo",
  "Kopanino",
  "Kopnica",
  "Kornatka",
  "Kosierzewo",
  "Kostrzewa",
  "Kostrzewa",
  "Koszalin",
  "Kotłowo",
  "Kowańcz",
  "Lipiany",
  "Łobez",
  "Łubowo",
  "Maszewo",
  "Mielno",
  "Mierzyn",
  "Mieszkowice",
  "Międzyzdroje",
  "Mirosławiec",
  "Moczkowo",
  "Moryń",
  "Mosty",
  "Mrzeżyno",
  "Mścice",
  "Myślibórz",
  "Nowe Warpno",
  "Nowogard",
  "Pełczyce",
  "Pęzino",
  "Płoty",
  "Pobierowo",
  "Polanów",
  "Police",
  "Połczyn-Zdrój",
  "Przecław",
  "Przybiernów",
  "Pyrzyce",
  "Radowo Małe",
  "Rąbino",
  "Recz",
  "Redło",
  "Resko",
  "Rosnowo",
  "Rymań",
  "Sianów",
  "Sławno",
  "Sławoborze",
  "Stare Bielice",
  "Stargard",
  "Stepnica",
  "Suchań",
  "Szczecin",
  "Szczecinek",
  "Świdwin",
  "Świnoujście",
  "Tanowo",
  "Trzcińsko-Zdrój",
  "Trzebiatów",
  "Trzebież",
  "Tuczno",
  "Turowo",
  "Tychowo",
  "Ustronie Morskie",
  "Wałcz",
  "Warszkowo",
  "Warzymice",
  "Węgorzyno",
  "Widuchowa",
  "Wierzchowo",
  "Wolin",
  "Wołczkowo",
  "Zieleniewo",
  "Złocieniec",
  "Żabów",
];

async function main() {
  const socialMediaPlatforms = [
    {
      name: "Facebook",
      placeholder: "https://www.facebook.com/yourname",
    },
    {
      name: "Twitter",
      placeholder: "https://twitter.com/yourname",
    },
    {
      name: "Instagram",
      placeholder: "https://instagram.com/yourname",
    },
    {
      name: "YouTube",
      placeholder: "https://www.facebook.com/yourname",
    },
  ];

  for (const platform of socialMediaPlatforms) {
    await prisma.socialMediaPlatform.create({
      data: platform,
    });
  }

  // Topics
  const topics = [
    "Atrakcje wodne",
    "Bajki",
    "Bohaterowie",
    "Dinozaury",
    "Historia",
    "Karuzele i rollercoastery",
    "Kopalnia",
    "Kosmos",
    "Kultura i sztuka",
    "Militaria",
    "Nauka",
    "Obiekty poprzemysłowe",
    "Obiekty zabytkowe",
    "Pociągi",
    "Pojazdy",
    "Przyroda",
    "Rycerze i księżniczki",
    "Samoloty",
    "Sport",
    "Statki",
    "Zabytki techniki",
    "Zoo i parki dzikiej przyrody",
    "Szlaki piesze i rowerowe",
    "Street art i sztuka miejska",
    "Rekreacja na łonie natury",
    "Podróże w czasie (miejsca historyczne)",
    "Muzyka i koncerty",
    "Innowacje i technologia",
  ];

  for (const topic of topics) {
    await prisma.topic.create({
      data: { name: topic },
    });
  }

  const tags = [
    "Bezpłatne wejście",
    "Dostępne dla osób niepełnosprawnych",
    "Automat z jedzeniem",
    "Miejsce na piknik",
    "Dostępny parking dla autokarów",
    "Edukacyjne",
    "Miejsce przyjazne zwierzętom",
    "Na cały dzień",
    "Na niepogodę",
    "Na świeżym powietrzu",
    "Otwarte sezonowo",
    "Parking",
    "Parking rowerowy",
    "Punkt gastronomiczny",
    "Warsztaty",
    "Wi-Fi",
    "Zwiedzanie z audioprzewodnikiem",
    "Zwiedzanie z przewodnikiem",
    "Wypożyczalnia sprzętu (np. rowery, łódki)",
  ];

  for (const tagName of tags) {
    await prisma.tag.create({
      data: {
        name: tagName,
      },
    });
  }

  const categories = [
    {
      name: "Zamki i  pałace",
      iconPath: "/categories/markers/castle.png",
      imagePath: "/categories/images/castle.png",
      description: "This property is close to the beach!",
    },
    {
      name: "Jeziora i zbiorniki",
      iconPath: "/categories/markers/lake.png",
      imagePath: "/categories/images/lake.png",
      description: "This property is has windmills!",
    },
    {
      name: "Jaskinie",
      iconPath: "/categories/markers/cave.png",
      imagePath: "/categories/images/cave.png",
      description: "This property is modern!",
    },
    {
      name: "Atrakcje",
      iconPath: "/categories/markers/fun.png",
      imagePath: "/categories/images/fun.png",
      description: "This property is in the countryside!",
    },
    {
      name: "Parki narodowe / Skwery",
      iconPath: "/categories/markers/park.png",
      imagePath: "/categories/images/park.png",
      description: "This is property has a beautiful pool!",
    },
    {
      name: "Pustynie",
      iconPath: "/categories/markers/beach.png",
      imagePath: "/categories/images/beach.png",
      description: "This property is near a lake!",
    },
    {
      name: "Parki wodne",
      iconPath: "/categories/markers/waterpark.png",
      imagePath: "/categories/images/waterpark.png",
      description: "This property has skiing activies!",
    },
    {
      name: "Muzea i galerie sztuki",
      iconPath: "/categories/markers/museum.png",
      imagePath: "/categories/images/museum.png",
      description: "This property is an ancient castle!",
    },
    {
      name: "Ogrody",
      iconPath: "/categories/markers/garden.png",
      imagePath: "/categories/images/garden.png",
      description: "This property is an ancient castle!",
    },
    {
      name: "Kopalnie",
      iconPath: "/categories/markers/mine.png",
      imagePath: "/categories/images/mine.png",
      description: "This property is an ancient castle!",
    },
    {
      name: "Jedzenie",
      iconPath: "/categories/markers/fun.png",
      imagePath: "/categories/images/fun.png",
      description: "This property is in the countryside!",
    },
    {
      name: "Nocleg",
      iconPath: "/categories/markers/fun.png",
      imagePath: "/categories/images/fun.png",
      description: "This property is in the countryside!",
    },
  ];

  for (const category of categories) {
    await prisma.category.create({
      data: category,
    });
  }

  // Provinces of Poland
  const provinces = [
    "Dolnośląskie",
    "Kujawsko-Pomorskie",
    "Lubelskie",
    "Lubuskie",
    "Łódzkie",
    "Małopolskie",
    "Mazowieckie",
    "Opolskie",
    "Podkarpackie",
    "Podlaskie",
    "Pomorskie",
    "Śląskie",
    "Świętokrzyskie",
    "Warmińsko-Mazurskie",
    "Wielkopolskie",
    "Zachodniopomorskie",
  ];

  for (const province of provinces) {
    await prisma.province.create({
      data: { name: province },
    });
  }

  const provinceCitiesMap = {
    Dolnośląskie: cities_of_dolnoslaskie_province,
    "Kujawsko-Pomorskie": cities_of_kujawsko_pomorskie_province,
    Lubelskie: cities_of_lubelskie_province,
    Lubuskie: cities_of_lubuskie_province,
    Łódzkie: cities_of_lodzkie_province,
    Małopolskie: cities_of_malopolskie_province,
    Mazowieckie: cities_of_mazowieckie_province,
    Opolskie: cities_of_opolskie_province,
    Podkarpackie: cities_of_podkarpackie_province,
    Podlaskie: cities_of_podlaskie_province,
    Pomorskie: cities_of_pomorskie_province,
    Śląskie: cities_of_slaskie_province,
    Świętokrzyskie: cities_of_swietokrzyskie_province,
    "Warmińsko-Mazurskie": cities_of_warminsko_mazurskie_province,
    Wielkopolskie: cities_of_wielkopolskie_province,
    Zachodniopomorskie: cities_of_zachodniopomorskie_province,
  };

  for (const [provinceName, cities] of Object.entries(provinceCitiesMap)) {
    const province = await prisma.province.findUnique({
      where: { name: provinceName },
    });

    if (!province) {
      console.log(`Prowincja '${provinceName}' nie została znaleziona.`);
      continue;
    }

    const cityObjects = cities.map((cityName) => ({
      name: cityName,
      provinceId: province.id,
    }));

    await prisma.city.createMany({
      data: cityObjects,
      skipDuplicates: true,
    });
  }
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
